//// Generated by aion generate — do not edit; regenerate from the project's types module.
////
//// JSON codecs for the `{{name}}` boundary types declared in
//// `src/{{name}}_io.gleam`: per type, a schema-shaped encoder/decoder
//// pair and a typed codec for activity and workflow I/O.

import aion/codec
import gleam/dynamic/decode
import gleam/json
import {{name}}_io as io

/// Encodes `io.AgentStatus` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn agent_status_to_json(value: io.AgentStatus) -> json.Json {
  json.object([
    #("stage", json.string(value.stage)),
    #("task_id", json.string(value.task_id)),
  ])
}

/// Decoder for `io.AgentStatus` from schema-shaped JSON.
pub fn agent_status_decoder() -> decode.Decoder(io.AgentStatus) {
  use field_stage <- decode.field("stage", decode.string)
  use field_task_id <- decode.field("task_id", decode.string)
  decode.success(io.AgentStatus(
    stage: field_stage,
    task_id: field_task_id,
  ))
}

/// Typed codec for `io.AgentStatus` (activity and workflow I/O).
pub fn agent_status_codec() -> codec.Codec(io.AgentStatus) {
  codec.json_codec(agent_status_to_json, agent_status_decoder())
}

/// Encodes `io.Decision` as its wire string.
pub fn decision_to_json(value: io.Decision) -> json.Json {
  case value {
    io.Approve -> json.string("approve")
    io.Reject -> json.string("reject")
  }
}

/// Decoder for `io.Decision` from its wire string.
pub fn decision_decoder() -> decode.Decoder(io.Decision) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "approve" -> decode.success(io.Approve)
      "reject" -> decode.success(io.Reject)
      _ -> decode.failure(io.Approve, "Decision")
    }
  })
}

/// Typed codec for `io.Decision` (activity and workflow I/O).
pub fn decision_codec() -> codec.Codec(io.Decision) {
  codec.json_codec(decision_to_json, decision_decoder())
}

/// Encodes `io.Input` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn input_to_json(value: io.Input) -> json.Json {
  json.object([
    #("task_id", json.string(value.task_id)),
    #("scout_prompt", json.string(value.scout_prompt)),
    #("act_prompt", json.string(value.act_prompt)),
    #("verify_prompt", json.string(value.verify_prompt)),
    #("review_timeout_ms", json.int(value.review_timeout_ms)),
  ])
}

/// Decoder for `io.Input` from schema-shaped JSON.
pub fn input_decoder() -> decode.Decoder(io.Input) {
  use field_task_id <- decode.field("task_id", decode.string)
  use field_scout_prompt <- decode.field("scout_prompt", decode.string)
  use field_act_prompt <- decode.field("act_prompt", decode.string)
  use field_verify_prompt <- decode.field("verify_prompt", decode.string)
  use field_review_timeout_ms <- decode.field("review_timeout_ms", decode.int)
  decode.success(io.Input(
    task_id: field_task_id,
    scout_prompt: field_scout_prompt,
    act_prompt: field_act_prompt,
    verify_prompt: field_verify_prompt,
    review_timeout_ms: field_review_timeout_ms,
  ))
}

/// Typed codec for `io.Input` (activity and workflow I/O).
pub fn input_codec() -> codec.Codec(io.Input) {
  codec.json_codec(input_to_json, input_decoder())
}

/// Encodes `io.Output` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn output_to_json(value: io.Output) -> json.Json {
  json.object([
    #("task_id", json.string(value.task_id)),
    #("disposition", json.string(value.disposition)),
    #("scout_finding", json.string(value.scout_finding)),
    #("act_artifact", json.string(value.act_artifact)),
    #("verify_verdict", json.string(value.verify_verdict)),
    #("reviewed_by", json.string(value.reviewed_by)),
    #("reason", json.string(value.reason)),
  ])
}

/// Decoder for `io.Output` from schema-shaped JSON.
pub fn output_decoder() -> decode.Decoder(io.Output) {
  use field_task_id <- decode.field("task_id", decode.string)
  use field_disposition <- decode.field("disposition", decode.string)
  use field_scout_finding <- decode.field("scout_finding", decode.string)
  use field_act_artifact <- decode.field("act_artifact", decode.string)
  use field_verify_verdict <- decode.field("verify_verdict", decode.string)
  use field_reviewed_by <- decode.field("reviewed_by", decode.string)
  use field_reason <- decode.field("reason", decode.string)
  decode.success(io.Output(
    task_id: field_task_id,
    disposition: field_disposition,
    scout_finding: field_scout_finding,
    act_artifact: field_act_artifact,
    verify_verdict: field_verify_verdict,
    reviewed_by: field_reviewed_by,
    reason: field_reason,
  ))
}

/// Typed codec for `io.Output` (activity and workflow I/O).
pub fn output_codec() -> codec.Codec(io.Output) {
  codec.json_codec(output_to_json, output_decoder())
}

/// Encodes `io.ReviewSignal` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn review_signal_to_json(value: io.ReviewSignal) -> json.Json {
  json.object([
    #("decision", decision_to_json(value.decision)),
    #("reviewer", json.string(value.reviewer)),
  ])
}

/// Decoder for `io.ReviewSignal` from schema-shaped JSON.
pub fn review_signal_decoder() -> decode.Decoder(io.ReviewSignal) {
  use field_decision <- decode.field("decision", decision_decoder())
  use field_reviewer <- decode.field("reviewer", decode.string)
  decode.success(io.ReviewSignal(
    decision: field_decision,
    reviewer: field_reviewer,
  ))
}

/// Typed codec for `io.ReviewSignal` (activity and workflow I/O).
pub fn review_signal_codec() -> codec.Codec(io.ReviewSignal) {
  codec.json_codec(review_signal_to_json, review_signal_decoder())
}

/// Encodes `io.StepInput` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn step_input_to_json(value: io.StepInput) -> json.Json {
  json.object([
    #("task_id", json.string(value.task_id)),
    #("prompt", json.string(value.prompt)),
    #("context", json.string(value.context)),
  ])
}

/// Decoder for `io.StepInput` from schema-shaped JSON.
pub fn step_input_decoder() -> decode.Decoder(io.StepInput) {
  use field_task_id <- decode.field("task_id", decode.string)
  use field_prompt <- decode.field("prompt", decode.string)
  use field_context <- decode.field("context", decode.string)
  decode.success(io.StepInput(
    task_id: field_task_id,
    prompt: field_prompt,
    context: field_context,
  ))
}

/// Typed codec for `io.StepInput` (activity and workflow I/O).
pub fn step_input_codec() -> codec.Codec(io.StepInput) {
  codec.json_codec(step_input_to_json, step_input_decoder())
}

/// Encodes `io.StepOutput` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn step_output_to_json(value: io.StepOutput) -> json.Json {
  json.object([
    #("result", json.string(value.result)),
  ])
}

/// Decoder for `io.StepOutput` from schema-shaped JSON.
pub fn step_output_decoder() -> decode.Decoder(io.StepOutput) {
  use field_result <- decode.field("result", decode.string)
  decode.success(io.StepOutput(
    result: field_result,
  ))
}

/// Typed codec for `io.StepOutput` (activity and workflow I/O).
pub fn step_output_codec() -> codec.Codec(io.StepOutput) {
  codec.json_codec(step_output_to_json, step_output_decoder())
}
