//// Generated by aion generate — do not edit; regenerate from the project's types module.
////
//// JSON codecs for the `{{name}}` boundary types declared in
//// `src/{{name}}_io.gleam`: per type, a schema-shaped encoder/decoder
//// pair and a typed codec for activity and workflow I/O.

import aion/codec
import gleam/dynamic/decode
import gleam/json
import gleam/list
import gleam/option
import {{name}}_io as io

/// Encodes `io.DevInput` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn dev_input_to_json(value: io.DevInput) -> json.Json {
  json.object([
    #("workspace", dev_input_workspace_to_json(value.workspace)),
    #("brief", json.string(value.brief)),
    #("design", json.string(value.design)),
    #("checklist", json.string(value.checklist)),
    #("stories", json.array(value.stories, json.string)),
    #("verify_fix_cap", json.int(value.verify_fix_cap)),
    #("round_backoff_ms", json.int(value.round_backoff_ms)),
  ])
}

/// Decoder for `io.DevInput` from schema-shaped JSON.
pub fn dev_input_decoder() -> decode.Decoder(io.DevInput) {
  use field_workspace <- decode.field("workspace", dev_input_workspace_decoder())
  use field_brief <- decode.field("brief", decode.string)
  use field_design <- decode.field("design", decode.string)
  use field_checklist <- decode.field("checklist", decode.string)
  use field_stories <- decode.field("stories", decode.list(decode.string))
  use field_verify_fix_cap <- decode.field("verify_fix_cap", decode.int)
  use field_round_backoff_ms <- decode.field("round_backoff_ms", decode.int)
  decode.success(io.DevInput(
    workspace: field_workspace,
    brief: field_brief,
    design: field_design,
    checklist: field_checklist,
    stories: field_stories,
    verify_fix_cap: field_verify_fix_cap,
    round_backoff_ms: field_round_backoff_ms,
  ))
}

/// Typed codec for `io.DevInput` (activity and workflow I/O).
pub fn dev_input_codec() -> codec.Codec(io.DevInput) {
  codec.json_codec(dev_input_to_json, dev_input_decoder())
}

/// Encodes `io.DevInputWorkspace` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn dev_input_workspace_to_json(value: io.DevInputWorkspace) -> json.Json {
  json.object([
    #("path", json.string(value.path)),
    #("branch", json.string(value.branch)),
    #("placement", dev_input_workspace_placement_to_json(value.placement)),
    #("isolation", dev_input_workspace_isolation_to_json(value.isolation)),
  ])
}

/// Decoder for `io.DevInputWorkspace` from schema-shaped JSON.
pub fn dev_input_workspace_decoder() -> decode.Decoder(io.DevInputWorkspace) {
  use field_path <- decode.field("path", decode.string)
  use field_branch <- decode.field("branch", decode.string)
  use field_placement <- decode.field("placement", dev_input_workspace_placement_decoder())
  use field_isolation <- decode.field("isolation", dev_input_workspace_isolation_decoder())
  decode.success(io.DevInputWorkspace(
    path: field_path,
    branch: field_branch,
    placement: field_placement,
    isolation: field_isolation,
  ))
}

/// Typed codec for `io.DevInputWorkspace` (activity and workflow I/O).
pub fn dev_input_workspace_codec() -> codec.Codec(io.DevInputWorkspace) {
  codec.json_codec(dev_input_workspace_to_json, dev_input_workspace_decoder())
}

/// Encodes `io.DevInputWorkspaceIsolation` as its wire string.
pub fn dev_input_workspace_isolation_to_json(value: io.DevInputWorkspaceIsolation) -> json.Json {
  case value {
    io.DevInputWorkspaceIsolationWorktree -> json.string("worktree")
    io.DevInputWorkspaceIsolationCopy -> json.string("copy")
    io.DevInputWorkspaceIsolationOverlay -> json.string("overlay")
    io.DevInputWorkspaceIsolationVm -> json.string("vm")
  }
}

/// Decoder for `io.DevInputWorkspaceIsolation` from its wire string.
pub fn dev_input_workspace_isolation_decoder() -> decode.Decoder(io.DevInputWorkspaceIsolation) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "worktree" -> decode.success(io.DevInputWorkspaceIsolationWorktree)
      "copy" -> decode.success(io.DevInputWorkspaceIsolationCopy)
      "overlay" -> decode.success(io.DevInputWorkspaceIsolationOverlay)
      "vm" -> decode.success(io.DevInputWorkspaceIsolationVm)
      _ -> decode.failure(io.DevInputWorkspaceIsolationWorktree, "DevInputWorkspaceIsolation")
    }
  })
}

/// Typed codec for `io.DevInputWorkspaceIsolation` (activity and workflow I/O).
pub fn dev_input_workspace_isolation_codec() -> codec.Codec(io.DevInputWorkspaceIsolation) {
  codec.json_codec(dev_input_workspace_isolation_to_json, dev_input_workspace_isolation_decoder())
}

/// Encodes `io.DevInputWorkspacePlacement` as its wire string.
pub fn dev_input_workspace_placement_to_json(value: io.DevInputWorkspacePlacement) -> json.Json {
  case value {
    io.DevInputWorkspacePlacementLocal -> json.string("local")
    io.DevInputWorkspacePlacementRemote -> json.string("remote")
  }
}

/// Decoder for `io.DevInputWorkspacePlacement` from its wire string.
pub fn dev_input_workspace_placement_decoder() -> decode.Decoder(io.DevInputWorkspacePlacement) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "local" -> decode.success(io.DevInputWorkspacePlacementLocal)
      "remote" -> decode.success(io.DevInputWorkspacePlacementRemote)
      _ -> decode.failure(io.DevInputWorkspacePlacementLocal, "DevInputWorkspacePlacement")
    }
  })
}

/// Typed codec for `io.DevInputWorkspacePlacement` (activity and workflow I/O).
pub fn dev_input_workspace_placement_codec() -> codec.Codec(io.DevInputWorkspacePlacement) {
  codec.json_codec(dev_input_workspace_placement_to_json, dev_input_workspace_placement_decoder())
}

/// Encodes `io.DevOutput` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn dev_output_to_json(value: io.DevOutput) -> json.Json {
  json.object([
    #("dev_result", dev_output_dev_result_to_json(value.dev_result)),
    #("build_warm", dev_output_build_warm_to_json(value.build_warm)),
    #("verify_rounds", json.int(value.verify_rounds)),
  ])
}

/// Decoder for `io.DevOutput` from schema-shaped JSON.
pub fn dev_output_decoder() -> decode.Decoder(io.DevOutput) {
  use field_dev_result <- decode.field("dev_result", dev_output_dev_result_decoder())
  use field_build_warm <- decode.field("build_warm", dev_output_build_warm_decoder())
  use field_verify_rounds <- decode.field("verify_rounds", decode.int)
  decode.success(io.DevOutput(
    dev_result: field_dev_result,
    build_warm: field_build_warm,
    verify_rounds: field_verify_rounds,
  ))
}

/// Typed codec for `io.DevOutput` (activity and workflow I/O).
pub fn dev_output_codec() -> codec.Codec(io.DevOutput) {
  codec.json_codec(dev_output_to_json, dev_output_decoder())
}

/// Encodes `io.DevOutputBuildWarm` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn dev_output_build_warm_to_json(value: io.DevOutputBuildWarm) -> json.Json {
  json.object([
    #("ok", json.bool(value.ok)),
    #("duration_ms", json.int(value.duration_ms)),
  ])
}

/// Decoder for `io.DevOutputBuildWarm` from schema-shaped JSON.
pub fn dev_output_build_warm_decoder() -> decode.Decoder(io.DevOutputBuildWarm) {
  use field_ok <- decode.field("ok", decode.bool)
  use field_duration_ms <- decode.field("duration_ms", decode.int)
  decode.success(io.DevOutputBuildWarm(
    ok: field_ok,
    duration_ms: field_duration_ms,
  ))
}

/// Typed codec for `io.DevOutputBuildWarm` (activity and workflow I/O).
pub fn dev_output_build_warm_codec() -> codec.Codec(io.DevOutputBuildWarm) {
  codec.json_codec(dev_output_build_warm_to_json, dev_output_build_warm_decoder())
}

/// Encodes `io.DevOutputDevResult` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn dev_output_dev_result_to_json(value: io.DevOutputDevResult) -> json.Json {
  json.object([
    #("session_id", json.string(value.session_id)),
    #("files_touched", json.array(value.files_touched, json.string)),
    #("summary", json.string(value.summary)),
  ])
}

/// Decoder for `io.DevOutputDevResult` from schema-shaped JSON.
pub fn dev_output_dev_result_decoder() -> decode.Decoder(io.DevOutputDevResult) {
  use field_session_id <- decode.field("session_id", decode.string)
  use field_files_touched <- decode.field("files_touched", decode.list(decode.string))
  use field_summary <- decode.field("summary", decode.string)
  decode.success(io.DevOutputDevResult(
    session_id: field_session_id,
    files_touched: field_files_touched,
    summary: field_summary,
  ))
}

/// Typed codec for `io.DevOutputDevResult` (activity and workflow I/O).
pub fn dev_output_dev_result_codec() -> codec.Codec(io.DevOutputDevResult) {
  codec.json_codec(dev_output_dev_result_to_json, dev_output_dev_result_decoder())
}

/// Encodes `io.GateInput` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn gate_input_to_json(value: io.GateInput) -> json.Json {
  json.object([
    #("workspace", gate_input_workspace_to_json(value.workspace)),
    #("files_touched", json.array(value.files_touched, json.string)),
    #("scope", gate_input_scope_to_json(value.scope)),
  ])
}

/// Decoder for `io.GateInput` from schema-shaped JSON.
pub fn gate_input_decoder() -> decode.Decoder(io.GateInput) {
  use field_workspace <- decode.field("workspace", gate_input_workspace_decoder())
  use field_files_touched <- decode.field("files_touched", decode.list(decode.string))
  use field_scope <- decode.field("scope", gate_input_scope_decoder())
  decode.success(io.GateInput(
    workspace: field_workspace,
    files_touched: field_files_touched,
    scope: field_scope,
  ))
}

/// Typed codec for `io.GateInput` (activity and workflow I/O).
pub fn gate_input_codec() -> codec.Codec(io.GateInput) {
  codec.json_codec(gate_input_to_json, gate_input_decoder())
}

/// Encodes `io.GateInputScope` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn gate_input_scope_to_json(value: io.GateInputScope) -> json.Json {
  json.object(
    list.flatten([
      [#("kind", gate_input_scope_kind_to_json(value.kind))],
      case value.modules {
        option.Some(present) -> [#("modules", json.array(present, json.string))]
        option.None -> []
      },
    ]),
  )
}

/// Decoder for `io.GateInputScope` from schema-shaped JSON.
pub fn gate_input_scope_decoder() -> decode.Decoder(io.GateInputScope) {
  use field_kind <- decode.field("kind", gate_input_scope_kind_decoder())
  use field_modules <- decode.optional_field(
    "modules",
    option.None,
    decode.optional(decode.list(decode.string)),
  )
  decode.success(io.GateInputScope(
    kind: field_kind,
    modules: field_modules,
  ))
}

/// Typed codec for `io.GateInputScope` (activity and workflow I/O).
pub fn gate_input_scope_codec() -> codec.Codec(io.GateInputScope) {
  codec.json_codec(gate_input_scope_to_json, gate_input_scope_decoder())
}

/// Encodes `io.GateInputScopeKind` as its wire string.
pub fn gate_input_scope_kind_to_json(value: io.GateInputScopeKind) -> json.Json {
  case value {
    io.GateInputScopeKindWorkspaceWide -> json.string("workspace_wide")
    io.GateInputScopeKindAffectedClosure -> json.string("affected_closure")
  }
}

/// Decoder for `io.GateInputScopeKind` from its wire string.
pub fn gate_input_scope_kind_decoder() -> decode.Decoder(io.GateInputScopeKind) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "workspace_wide" -> decode.success(io.GateInputScopeKindWorkspaceWide)
      "affected_closure" -> decode.success(io.GateInputScopeKindAffectedClosure)
      _ -> decode.failure(io.GateInputScopeKindWorkspaceWide, "GateInputScopeKind")
    }
  })
}

/// Typed codec for `io.GateInputScopeKind` (activity and workflow I/O).
pub fn gate_input_scope_kind_codec() -> codec.Codec(io.GateInputScopeKind) {
  codec.json_codec(gate_input_scope_kind_to_json, gate_input_scope_kind_decoder())
}

/// Encodes `io.GateInputWorkspace` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn gate_input_workspace_to_json(value: io.GateInputWorkspace) -> json.Json {
  json.object([
    #("path", json.string(value.path)),
    #("branch", json.string(value.branch)),
    #("placement", gate_input_workspace_placement_to_json(value.placement)),
    #("isolation", gate_input_workspace_isolation_to_json(value.isolation)),
  ])
}

/// Decoder for `io.GateInputWorkspace` from schema-shaped JSON.
pub fn gate_input_workspace_decoder() -> decode.Decoder(io.GateInputWorkspace) {
  use field_path <- decode.field("path", decode.string)
  use field_branch <- decode.field("branch", decode.string)
  use field_placement <- decode.field("placement", gate_input_workspace_placement_decoder())
  use field_isolation <- decode.field("isolation", gate_input_workspace_isolation_decoder())
  decode.success(io.GateInputWorkspace(
    path: field_path,
    branch: field_branch,
    placement: field_placement,
    isolation: field_isolation,
  ))
}

/// Typed codec for `io.GateInputWorkspace` (activity and workflow I/O).
pub fn gate_input_workspace_codec() -> codec.Codec(io.GateInputWorkspace) {
  codec.json_codec(gate_input_workspace_to_json, gate_input_workspace_decoder())
}

/// Encodes `io.GateInputWorkspaceIsolation` as its wire string.
pub fn gate_input_workspace_isolation_to_json(value: io.GateInputWorkspaceIsolation) -> json.Json {
  case value {
    io.GateInputWorkspaceIsolationWorktree -> json.string("worktree")
    io.GateInputWorkspaceIsolationCopy -> json.string("copy")
    io.GateInputWorkspaceIsolationOverlay -> json.string("overlay")
    io.GateInputWorkspaceIsolationVm -> json.string("vm")
  }
}

/// Decoder for `io.GateInputWorkspaceIsolation` from its wire string.
pub fn gate_input_workspace_isolation_decoder() -> decode.Decoder(io.GateInputWorkspaceIsolation) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "worktree" -> decode.success(io.GateInputWorkspaceIsolationWorktree)
      "copy" -> decode.success(io.GateInputWorkspaceIsolationCopy)
      "overlay" -> decode.success(io.GateInputWorkspaceIsolationOverlay)
      "vm" -> decode.success(io.GateInputWorkspaceIsolationVm)
      _ -> decode.failure(io.GateInputWorkspaceIsolationWorktree, "GateInputWorkspaceIsolation")
    }
  })
}

/// Typed codec for `io.GateInputWorkspaceIsolation` (activity and workflow I/O).
pub fn gate_input_workspace_isolation_codec() -> codec.Codec(io.GateInputWorkspaceIsolation) {
  codec.json_codec(gate_input_workspace_isolation_to_json, gate_input_workspace_isolation_decoder())
}

/// Encodes `io.GateInputWorkspacePlacement` as its wire string.
pub fn gate_input_workspace_placement_to_json(value: io.GateInputWorkspacePlacement) -> json.Json {
  case value {
    io.GateInputWorkspacePlacementLocal -> json.string("local")
    io.GateInputWorkspacePlacementRemote -> json.string("remote")
  }
}

/// Decoder for `io.GateInputWorkspacePlacement` from its wire string.
pub fn gate_input_workspace_placement_decoder() -> decode.Decoder(io.GateInputWorkspacePlacement) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "local" -> decode.success(io.GateInputWorkspacePlacementLocal)
      "remote" -> decode.success(io.GateInputWorkspacePlacementRemote)
      _ -> decode.failure(io.GateInputWorkspacePlacementLocal, "GateInputWorkspacePlacement")
    }
  })
}

/// Typed codec for `io.GateInputWorkspacePlacement` (activity and workflow I/O).
pub fn gate_input_workspace_placement_codec() -> codec.Codec(io.GateInputWorkspacePlacement) {
  codec.json_codec(gate_input_workspace_placement_to_json, gate_input_workspace_placement_decoder())
}

/// Encodes `io.GateOutput` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn gate_output_to_json(value: io.GateOutput) -> json.Json {
  json.object([
    #("verdict", gate_output_verdict_to_json(value.verdict)),
  ])
}

/// Decoder for `io.GateOutput` from schema-shaped JSON.
pub fn gate_output_decoder() -> decode.Decoder(io.GateOutput) {
  use field_verdict <- decode.field("verdict", gate_output_verdict_decoder())
  decode.success(io.GateOutput(
    verdict: field_verdict,
  ))
}

/// Typed codec for `io.GateOutput` (activity and workflow I/O).
pub fn gate_output_codec() -> codec.Codec(io.GateOutput) {
  codec.json_codec(gate_output_to_json, gate_output_decoder())
}

/// Encodes `io.GateOutputVerdict` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn gate_output_verdict_to_json(value: io.GateOutputVerdict) -> json.Json {
  json.object(
    list.flatten([
      [#("outcome", gate_output_verdict_outcome_to_json(value.outcome))],
      case value.report {
        option.Some(present) -> [#("report", json.string(present))]
        option.None -> []
      },
    ]),
  )
}

/// Decoder for `io.GateOutputVerdict` from schema-shaped JSON.
pub fn gate_output_verdict_decoder() -> decode.Decoder(io.GateOutputVerdict) {
  use field_outcome <- decode.field("outcome", gate_output_verdict_outcome_decoder())
  use field_report <- decode.optional_field(
    "report",
    option.None,
    decode.optional(decode.string),
  )
  decode.success(io.GateOutputVerdict(
    outcome: field_outcome,
    report: field_report,
  ))
}

/// Typed codec for `io.GateOutputVerdict` (activity and workflow I/O).
pub fn gate_output_verdict_codec() -> codec.Codec(io.GateOutputVerdict) {
  codec.json_codec(gate_output_verdict_to_json, gate_output_verdict_decoder())
}

/// Encodes `io.GateOutputVerdictOutcome` as its wire string.
pub fn gate_output_verdict_outcome_to_json(value: io.GateOutputVerdictOutcome) -> json.Json {
  case value {
    io.GateOutputVerdictOutcomePass -> json.string("pass")
    io.GateOutputVerdictOutcomeFail -> json.string("fail")
  }
}

/// Decoder for `io.GateOutputVerdictOutcome` from its wire string.
pub fn gate_output_verdict_outcome_decoder() -> decode.Decoder(io.GateOutputVerdictOutcome) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "pass" -> decode.success(io.GateOutputVerdictOutcomePass)
      "fail" -> decode.success(io.GateOutputVerdictOutcomeFail)
      _ -> decode.failure(io.GateOutputVerdictOutcomePass, "GateOutputVerdictOutcome")
    }
  })
}

/// Typed codec for `io.GateOutputVerdictOutcome` (activity and workflow I/O).
pub fn gate_output_verdict_outcome_codec() -> codec.Codec(io.GateOutputVerdictOutcome) {
  codec.json_codec(gate_output_verdict_outcome_to_json, gate_output_verdict_outcome_decoder())
}

/// Encodes `io.Input` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn input_to_json(value: io.Input) -> json.Json {
  json.object([
    #("repo_root", json.string(value.repo_root)),
    #("brief_id", json.string(value.brief_id)),
    #("reviewers", json.array(value.reviewers, json.string)),
    #("base_ref", json.string(value.base_ref)),
    #("placement", input_placement_to_json(value.placement)),
    #("isolation", input_isolation_to_json(value.isolation)),
    #("brief", json.string(value.brief)),
    #("design", json.string(value.design)),
    #("checklist", json.string(value.checklist)),
    #("stories", json.array(value.stories, json.string)),
    #("verify_fix_cap", json.int(value.verify_fix_cap)),
    #("review_cap", json.int(value.review_cap)),
    #("round_backoff_ms", json.int(value.round_backoff_ms)),
    #("review_deadline_ms", json.int(value.review_deadline_ms)),
  ])
}

/// Decoder for `io.Input` from schema-shaped JSON.
pub fn input_decoder() -> decode.Decoder(io.Input) {
  use field_repo_root <- decode.field("repo_root", decode.string)
  use field_brief_id <- decode.field("brief_id", decode.string)
  use field_reviewers <- decode.field("reviewers", decode.list(decode.string))
  use field_base_ref <- decode.field("base_ref", decode.string)
  use field_placement <- decode.field("placement", input_placement_decoder())
  use field_isolation <- decode.field("isolation", input_isolation_decoder())
  use field_brief <- decode.field("brief", decode.string)
  use field_design <- decode.field("design", decode.string)
  use field_checklist <- decode.field("checklist", decode.string)
  use field_stories <- decode.field("stories", decode.list(decode.string))
  use field_verify_fix_cap <- decode.field("verify_fix_cap", decode.int)
  use field_review_cap <- decode.field("review_cap", decode.int)
  use field_round_backoff_ms <- decode.field("round_backoff_ms", decode.int)
  use field_review_deadline_ms <- decode.field("review_deadline_ms", decode.int)
  decode.success(io.Input(
    repo_root: field_repo_root,
    brief_id: field_brief_id,
    reviewers: field_reviewers,
    base_ref: field_base_ref,
    placement: field_placement,
    isolation: field_isolation,
    brief: field_brief,
    design: field_design,
    checklist: field_checklist,
    stories: field_stories,
    verify_fix_cap: field_verify_fix_cap,
    review_cap: field_review_cap,
    round_backoff_ms: field_round_backoff_ms,
    review_deadline_ms: field_review_deadline_ms,
  ))
}

/// Typed codec for `io.Input` (activity and workflow I/O).
pub fn input_codec() -> codec.Codec(io.Input) {
  codec.json_codec(input_to_json, input_decoder())
}

/// Encodes `io.InputIsolation` as its wire string.
pub fn input_isolation_to_json(value: io.InputIsolation) -> json.Json {
  case value {
    io.InputIsolationWorktree -> json.string("worktree")
    io.InputIsolationCopy -> json.string("copy")
    io.InputIsolationOverlay -> json.string("overlay")
    io.InputIsolationVm -> json.string("vm")
  }
}

/// Decoder for `io.InputIsolation` from its wire string.
pub fn input_isolation_decoder() -> decode.Decoder(io.InputIsolation) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "worktree" -> decode.success(io.InputIsolationWorktree)
      "copy" -> decode.success(io.InputIsolationCopy)
      "overlay" -> decode.success(io.InputIsolationOverlay)
      "vm" -> decode.success(io.InputIsolationVm)
      _ -> decode.failure(io.InputIsolationWorktree, "InputIsolation")
    }
  })
}

/// Typed codec for `io.InputIsolation` (activity and workflow I/O).
pub fn input_isolation_codec() -> codec.Codec(io.InputIsolation) {
  codec.json_codec(input_isolation_to_json, input_isolation_decoder())
}

/// Encodes `io.InputPlacement` as its wire string.
pub fn input_placement_to_json(value: io.InputPlacement) -> json.Json {
  case value {
    io.InputPlacementLocal -> json.string("local")
    io.InputPlacementRemote -> json.string("remote")
  }
}

/// Decoder for `io.InputPlacement` from its wire string.
pub fn input_placement_decoder() -> decode.Decoder(io.InputPlacement) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "local" -> decode.success(io.InputPlacementLocal)
      "remote" -> decode.success(io.InputPlacementRemote)
      _ -> decode.failure(io.InputPlacementLocal, "InputPlacement")
    }
  })
}

/// Typed codec for `io.InputPlacement` (activity and workflow I/O).
pub fn input_placement_codec() -> codec.Codec(io.InputPlacement) {
  codec.json_codec(input_placement_to_json, input_placement_decoder())
}

/// Encodes `io.Output` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn output_to_json(value: io.Output) -> json.Json {
  json.object([
    #("branch", json.string(value.branch)),
    #("merged_into", json.string(value.merged_into)),
    #("session_id", json.string(value.session_id)),
    #("build_warm", output_build_warm_to_json(value.build_warm)),
    #("verify_rounds", json.int(value.verify_rounds)),
    #("review_rounds", json.int(value.review_rounds)),
  ])
}

/// Decoder for `io.Output` from schema-shaped JSON.
pub fn output_decoder() -> decode.Decoder(io.Output) {
  use field_branch <- decode.field("branch", decode.string)
  use field_merged_into <- decode.field("merged_into", decode.string)
  use field_session_id <- decode.field("session_id", decode.string)
  use field_build_warm <- decode.field("build_warm", output_build_warm_decoder())
  use field_verify_rounds <- decode.field("verify_rounds", decode.int)
  use field_review_rounds <- decode.field("review_rounds", decode.int)
  decode.success(io.Output(
    branch: field_branch,
    merged_into: field_merged_into,
    session_id: field_session_id,
    build_warm: field_build_warm,
    verify_rounds: field_verify_rounds,
    review_rounds: field_review_rounds,
  ))
}

/// Typed codec for `io.Output` (activity and workflow I/O).
pub fn output_codec() -> codec.Codec(io.Output) {
  codec.json_codec(output_to_json, output_decoder())
}

/// Encodes `io.OutputBuildWarm` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn output_build_warm_to_json(value: io.OutputBuildWarm) -> json.Json {
  json.object([
    #("ok", json.bool(value.ok)),
    #("duration_ms", json.int(value.duration_ms)),
  ])
}

/// Decoder for `io.OutputBuildWarm` from schema-shaped JSON.
pub fn output_build_warm_decoder() -> decode.Decoder(io.OutputBuildWarm) {
  use field_ok <- decode.field("ok", decode.bool)
  use field_duration_ms <- decode.field("duration_ms", decode.int)
  decode.success(io.OutputBuildWarm(
    ok: field_ok,
    duration_ms: field_duration_ms,
  ))
}

/// Typed codec for `io.OutputBuildWarm` (activity and workflow I/O).
pub fn output_build_warm_codec() -> codec.Codec(io.OutputBuildWarm) {
  codec.json_codec(output_build_warm_to_json, output_build_warm_decoder())
}
