//// Generated by aion codegen — do not edit; regenerate from schemas/.
////
//// Types and JSON codecs for the `aion_stacked_dev` workflow project,
//// derived from every `schemas/*.json` document in filename order.

import gleam/dynamic/decode
import gleam/json
import gleam/list
import gleam/option

/// Generated from `schemas/dev_report.json`.
pub type DevReport {
  DevReport(
    summary: String,
    commit_message: String,
    enrichments: List(DevReportEnrichmentsItem),
    attestation: DevReportAttestation,
  )
}

/// Encodes `DevReport` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn dev_report_to_json(value: DevReport) -> json.Json {
  json.object([
    #("summary", json.string(value.summary)),
    #("commit_message", json.string(value.commit_message)),
    #("enrichments", json.array(value.enrichments, dev_report_enrichments_item_to_json)),
    #("attestation", dev_report_attestation_to_json(value.attestation)),
  ])
}

/// Decoder for `DevReport` from schema-shaped JSON.
pub fn dev_report_decoder() -> decode.Decoder(DevReport) {
  use field_summary <- decode.field("summary", decode.string)
  use field_commit_message <- decode.field("commit_message", decode.string)
  use field_enrichments <- decode.field("enrichments", decode.list(dev_report_enrichments_item_decoder()))
  use field_attestation <- decode.field("attestation", dev_report_attestation_decoder())
  decode.success(DevReport(
    summary: field_summary,
    commit_message: field_commit_message,
    enrichments: field_enrichments,
    attestation: field_attestation,
  ))
}

/// Generated from `schemas/dev_report.json` at `/properties/enrichments/items`.
pub type DevReportEnrichmentsItem {
  DevReportEnrichmentsItem(
    id: String,
    status: DevReportEnrichmentsItemStatus,
    files_changed: List(DevReportEnrichmentsItemFilesChangedItem),
    how: String,
    deviation: String,
    checklist: List(DevReportEnrichmentsItemChecklistItem),
    stories: List(DevReportEnrichmentsItemStoriesItem),
  )
}

/// Encodes `DevReportEnrichmentsItem` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn dev_report_enrichments_item_to_json(value: DevReportEnrichmentsItem) -> json.Json {
  json.object([
    #("id", json.string(value.id)),
    #("status", dev_report_enrichments_item_status_to_json(value.status)),
    #("files_changed", json.array(value.files_changed, dev_report_enrichments_item_files_changed_item_to_json)),
    #("how", json.string(value.how)),
    #("deviation", json.string(value.deviation)),
    #("checklist", json.array(value.checklist, dev_report_enrichments_item_checklist_item_to_json)),
    #("stories", json.array(value.stories, dev_report_enrichments_item_stories_item_to_json)),
  ])
}

/// Decoder for `DevReportEnrichmentsItem` from schema-shaped JSON.
pub fn dev_report_enrichments_item_decoder() -> decode.Decoder(DevReportEnrichmentsItem) {
  use field_id <- decode.field("id", decode.string)
  use field_status <- decode.field("status", dev_report_enrichments_item_status_decoder())
  use field_files_changed <- decode.field("files_changed", decode.list(dev_report_enrichments_item_files_changed_item_decoder()))
  use field_how <- decode.field("how", decode.string)
  use field_deviation <- decode.field("deviation", decode.string)
  use field_checklist <- decode.field("checklist", decode.list(dev_report_enrichments_item_checklist_item_decoder()))
  use field_stories <- decode.field("stories", decode.list(dev_report_enrichments_item_stories_item_decoder()))
  decode.success(DevReportEnrichmentsItem(
    id: field_id,
    status: field_status,
    files_changed: field_files_changed,
    how: field_how,
    deviation: field_deviation,
    checklist: field_checklist,
    stories: field_stories,
  ))
}

/// Generated from `schemas/dev_report.json` at `/properties/enrichments/items/properties/status`.
pub type DevReportEnrichmentsItemStatus {
  DevReportEnrichmentsItemStatusImplemented
  DevReportEnrichmentsItemStatusBlocked
}

/// Encodes `DevReportEnrichmentsItemStatus` as its wire string.
pub fn dev_report_enrichments_item_status_to_json(value: DevReportEnrichmentsItemStatus) -> json.Json {
  case value {
    DevReportEnrichmentsItemStatusImplemented -> json.string("implemented")
    DevReportEnrichmentsItemStatusBlocked -> json.string("blocked")
  }
}

/// Decoder for `DevReportEnrichmentsItemStatus` from its wire string.
pub fn dev_report_enrichments_item_status_decoder() -> decode.Decoder(DevReportEnrichmentsItemStatus) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "implemented" -> decode.success(DevReportEnrichmentsItemStatusImplemented)
      "blocked" -> decode.success(DevReportEnrichmentsItemStatusBlocked)
      _ -> decode.failure(DevReportEnrichmentsItemStatusImplemented, "DevReportEnrichmentsItemStatus")
    }
  })
}

/// Generated from `schemas/dev_report.json` at `/properties/enrichments/items/properties/files_changed/items`.
pub type DevReportEnrichmentsItemFilesChangedItem {
  DevReportEnrichmentsItemFilesChangedItem(
    path: String,
    change: DevReportEnrichmentsItemFilesChangedItemChange,
    note: String,
  )
}

/// Encodes `DevReportEnrichmentsItemFilesChangedItem` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn dev_report_enrichments_item_files_changed_item_to_json(value: DevReportEnrichmentsItemFilesChangedItem) -> json.Json {
  json.object([
    #("path", json.string(value.path)),
    #("change", dev_report_enrichments_item_files_changed_item_change_to_json(value.change)),
    #("note", json.string(value.note)),
  ])
}

/// Decoder for `DevReportEnrichmentsItemFilesChangedItem` from schema-shaped JSON.
pub fn dev_report_enrichments_item_files_changed_item_decoder() -> decode.Decoder(DevReportEnrichmentsItemFilesChangedItem) {
  use field_path <- decode.field("path", decode.string)
  use field_change <- decode.field("change", dev_report_enrichments_item_files_changed_item_change_decoder())
  use field_note <- decode.field("note", decode.string)
  decode.success(DevReportEnrichmentsItemFilesChangedItem(
    path: field_path,
    change: field_change,
    note: field_note,
  ))
}

/// Generated from `schemas/dev_report.json` at `/properties/enrichments/items/properties/files_changed/items/properties/change`.
pub type DevReportEnrichmentsItemFilesChangedItemChange {
  DevReportEnrichmentsItemFilesChangedItemChangeCreated
  DevReportEnrichmentsItemFilesChangedItemChangeModified
  DevReportEnrichmentsItemFilesChangedItemChangeDeleted
}

/// Encodes `DevReportEnrichmentsItemFilesChangedItemChange` as its wire string.
pub fn dev_report_enrichments_item_files_changed_item_change_to_json(value: DevReportEnrichmentsItemFilesChangedItemChange) -> json.Json {
  case value {
    DevReportEnrichmentsItemFilesChangedItemChangeCreated -> json.string("created")
    DevReportEnrichmentsItemFilesChangedItemChangeModified -> json.string("modified")
    DevReportEnrichmentsItemFilesChangedItemChangeDeleted -> json.string("deleted")
  }
}

/// Decoder for `DevReportEnrichmentsItemFilesChangedItemChange` from its wire string.
pub fn dev_report_enrichments_item_files_changed_item_change_decoder() -> decode.Decoder(DevReportEnrichmentsItemFilesChangedItemChange) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "created" -> decode.success(DevReportEnrichmentsItemFilesChangedItemChangeCreated)
      "modified" -> decode.success(DevReportEnrichmentsItemFilesChangedItemChangeModified)
      "deleted" -> decode.success(DevReportEnrichmentsItemFilesChangedItemChangeDeleted)
      _ -> decode.failure(DevReportEnrichmentsItemFilesChangedItemChangeCreated, "DevReportEnrichmentsItemFilesChangedItemChange")
    }
  })
}

/// Generated from `schemas/dev_report.json` at `/properties/enrichments/items/properties/checklist/items`.
pub type DevReportEnrichmentsItemChecklistItem {
  DevReportEnrichmentsItemChecklistItem(
    id: String,
    done: Bool,
    note: String,
  )
}

/// Encodes `DevReportEnrichmentsItemChecklistItem` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn dev_report_enrichments_item_checklist_item_to_json(value: DevReportEnrichmentsItemChecklistItem) -> json.Json {
  json.object([
    #("id", json.string(value.id)),
    #("done", json.bool(value.done)),
    #("note", json.string(value.note)),
  ])
}

/// Decoder for `DevReportEnrichmentsItemChecklistItem` from schema-shaped JSON.
pub fn dev_report_enrichments_item_checklist_item_decoder() -> decode.Decoder(DevReportEnrichmentsItemChecklistItem) {
  use field_id <- decode.field("id", decode.string)
  use field_done <- decode.field("done", decode.bool)
  use field_note <- decode.field("note", decode.string)
  decode.success(DevReportEnrichmentsItemChecklistItem(
    id: field_id,
    done: field_done,
    note: field_note,
  ))
}

/// Generated from `schemas/dev_report.json` at `/properties/enrichments/items/properties/stories/items`.
pub type DevReportEnrichmentsItemStoriesItem {
  DevReportEnrichmentsItemStoriesItem(
    id: String,
    satisfied: Bool,
    note: String,
  )
}

/// Encodes `DevReportEnrichmentsItemStoriesItem` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn dev_report_enrichments_item_stories_item_to_json(value: DevReportEnrichmentsItemStoriesItem) -> json.Json {
  json.object([
    #("id", json.string(value.id)),
    #("satisfied", json.bool(value.satisfied)),
    #("note", json.string(value.note)),
  ])
}

/// Decoder for `DevReportEnrichmentsItemStoriesItem` from schema-shaped JSON.
pub fn dev_report_enrichments_item_stories_item_decoder() -> decode.Decoder(DevReportEnrichmentsItemStoriesItem) {
  use field_id <- decode.field("id", decode.string)
  use field_satisfied <- decode.field("satisfied", decode.bool)
  use field_note <- decode.field("note", decode.string)
  decode.success(DevReportEnrichmentsItemStoriesItem(
    id: field_id,
    satisfied: field_satisfied,
    note: field_note,
  ))
}

/// Generated from `schemas/dev_report.json` at `/properties/attestation`.
pub type DevReportAttestation {
  DevReportAttestation(
    no_panics: Bool,
    no_unsafe: Bool,
    boundaries_respected: Bool,
    tests_pass: Bool,
  )
}

/// Encodes `DevReportAttestation` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn dev_report_attestation_to_json(value: DevReportAttestation) -> json.Json {
  json.object([
    #("no_panics", json.bool(value.no_panics)),
    #("no_unsafe", json.bool(value.no_unsafe)),
    #("boundaries_respected", json.bool(value.boundaries_respected)),
    #("tests_pass", json.bool(value.tests_pass)),
  ])
}

/// Decoder for `DevReportAttestation` from schema-shaped JSON.
pub fn dev_report_attestation_decoder() -> decode.Decoder(DevReportAttestation) {
  use field_no_panics <- decode.field("no_panics", decode.bool)
  use field_no_unsafe <- decode.field("no_unsafe", decode.bool)
  use field_boundaries_respected <- decode.field("boundaries_respected", decode.bool)
  use field_tests_pass <- decode.field("tests_pass", decode.bool)
  decode.success(DevReportAttestation(
    no_panics: field_no_panics,
    no_unsafe: field_no_unsafe,
    boundaries_respected: field_boundaries_respected,
    tests_pass: field_tests_pass,
  ))
}

/// Generated from `schemas/gate_input.json`.
pub type GateInput {
  GateInput(
    workspace: GateInputWorkspace,
    files_touched: List(String),
    scope: GateInputScope,
  )
}

/// Encodes `GateInput` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn gate_input_to_json(value: GateInput) -> json.Json {
  json.object([
    #("workspace", gate_input_workspace_to_json(value.workspace)),
    #("files_touched", json.array(value.files_touched, json.string)),
    #("scope", gate_input_scope_to_json(value.scope)),
  ])
}

/// Decoder for `GateInput` from schema-shaped JSON.
pub fn gate_input_decoder() -> decode.Decoder(GateInput) {
  use field_workspace <- decode.field("workspace", gate_input_workspace_decoder())
  use field_files_touched <- decode.field("files_touched", decode.list(decode.string))
  use field_scope <- decode.field("scope", gate_input_scope_decoder())
  decode.success(GateInput(
    workspace: field_workspace,
    files_touched: field_files_touched,
    scope: field_scope,
  ))
}

/// Generated from `schemas/gate_input.json` at `/properties/workspace`.
pub type GateInputWorkspace {
  GateInputWorkspace(
    path: String,
    branch: String,
    placement: GateInputWorkspacePlacement,
    isolation: GateInputWorkspaceIsolation,
  )
}

/// Encodes `GateInputWorkspace` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn gate_input_workspace_to_json(value: GateInputWorkspace) -> json.Json {
  json.object([
    #("path", json.string(value.path)),
    #("branch", json.string(value.branch)),
    #("placement", gate_input_workspace_placement_to_json(value.placement)),
    #("isolation", gate_input_workspace_isolation_to_json(value.isolation)),
  ])
}

/// Decoder for `GateInputWorkspace` from schema-shaped JSON.
pub fn gate_input_workspace_decoder() -> decode.Decoder(GateInputWorkspace) {
  use field_path <- decode.field("path", decode.string)
  use field_branch <- decode.field("branch", decode.string)
  use field_placement <- decode.field("placement", gate_input_workspace_placement_decoder())
  use field_isolation <- decode.field("isolation", gate_input_workspace_isolation_decoder())
  decode.success(GateInputWorkspace(
    path: field_path,
    branch: field_branch,
    placement: field_placement,
    isolation: field_isolation,
  ))
}

/// Generated from `schemas/gate_input.json` at `/properties/workspace/properties/placement`.
pub type GateInputWorkspacePlacement {
  GateInputWorkspacePlacementLocal
  GateInputWorkspacePlacementRemote
}

/// Encodes `GateInputWorkspacePlacement` as its wire string.
pub fn gate_input_workspace_placement_to_json(value: GateInputWorkspacePlacement) -> json.Json {
  case value {
    GateInputWorkspacePlacementLocal -> json.string("local")
    GateInputWorkspacePlacementRemote -> json.string("remote")
  }
}

/// Decoder for `GateInputWorkspacePlacement` from its wire string.
pub fn gate_input_workspace_placement_decoder() -> decode.Decoder(GateInputWorkspacePlacement) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "local" -> decode.success(GateInputWorkspacePlacementLocal)
      "remote" -> decode.success(GateInputWorkspacePlacementRemote)
      _ -> decode.failure(GateInputWorkspacePlacementLocal, "GateInputWorkspacePlacement")
    }
  })
}

/// Generated from `schemas/gate_input.json` at `/properties/workspace/properties/isolation`.
pub type GateInputWorkspaceIsolation {
  GateInputWorkspaceIsolationWorktree
  GateInputWorkspaceIsolationCopy
  GateInputWorkspaceIsolationOverlay
  GateInputWorkspaceIsolationVm
}

/// Encodes `GateInputWorkspaceIsolation` as its wire string.
pub fn gate_input_workspace_isolation_to_json(value: GateInputWorkspaceIsolation) -> json.Json {
  case value {
    GateInputWorkspaceIsolationWorktree -> json.string("worktree")
    GateInputWorkspaceIsolationCopy -> json.string("copy")
    GateInputWorkspaceIsolationOverlay -> json.string("overlay")
    GateInputWorkspaceIsolationVm -> json.string("vm")
  }
}

/// Decoder for `GateInputWorkspaceIsolation` from its wire string.
pub fn gate_input_workspace_isolation_decoder() -> decode.Decoder(GateInputWorkspaceIsolation) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "worktree" -> decode.success(GateInputWorkspaceIsolationWorktree)
      "copy" -> decode.success(GateInputWorkspaceIsolationCopy)
      "overlay" -> decode.success(GateInputWorkspaceIsolationOverlay)
      "vm" -> decode.success(GateInputWorkspaceIsolationVm)
      _ -> decode.failure(GateInputWorkspaceIsolationWorktree, "GateInputWorkspaceIsolation")
    }
  })
}

/// Generated from `schemas/gate_input.json` at `/properties/scope`.
pub type GateInputScope {
  GateInputScope(
    kind: GateInputScopeKind,
    modules: option.Option(List(String)),
  )
}

/// Encodes `GateInputScope` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn gate_input_scope_to_json(value: GateInputScope) -> json.Json {
  json.object(
    list.flatten([
      [#("kind", gate_input_scope_kind_to_json(value.kind))],
      case value.modules {
        option.Some(present) -> [#("modules", json.array(present, json.string))]
        option.None -> []
      },
    ]),
  )
}

/// Decoder for `GateInputScope` from schema-shaped JSON.
pub fn gate_input_scope_decoder() -> decode.Decoder(GateInputScope) {
  use field_kind <- decode.field("kind", gate_input_scope_kind_decoder())
  use field_modules <- decode.optional_field(
    "modules",
    option.None,
    decode.optional(decode.list(decode.string)),
  )
  decode.success(GateInputScope(
    kind: field_kind,
    modules: field_modules,
  ))
}

/// Generated from `schemas/gate_input.json` at `/properties/scope/properties/kind`.
pub type GateInputScopeKind {
  GateInputScopeKindWorkspaceWide
  GateInputScopeKindAffectedClosure
}

/// Encodes `GateInputScopeKind` as its wire string.
pub fn gate_input_scope_kind_to_json(value: GateInputScopeKind) -> json.Json {
  case value {
    GateInputScopeKindWorkspaceWide -> json.string("workspace_wide")
    GateInputScopeKindAffectedClosure -> json.string("affected_closure")
  }
}

/// Decoder for `GateInputScopeKind` from its wire string.
pub fn gate_input_scope_kind_decoder() -> decode.Decoder(GateInputScopeKind) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "workspace_wide" -> decode.success(GateInputScopeKindWorkspaceWide)
      "affected_closure" -> decode.success(GateInputScopeKindAffectedClosure)
      _ -> decode.failure(GateInputScopeKindWorkspaceWide, "GateInputScopeKind")
    }
  })
}

/// Generated from `schemas/gate_output.json`.
pub type GateOutput {
  GateOutput(
    verdict: GateOutputVerdict,
  )
}

/// Encodes `GateOutput` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn gate_output_to_json(value: GateOutput) -> json.Json {
  json.object([
    #("verdict", gate_output_verdict_to_json(value.verdict)),
  ])
}

/// Decoder for `GateOutput` from schema-shaped JSON.
pub fn gate_output_decoder() -> decode.Decoder(GateOutput) {
  use field_verdict <- decode.field("verdict", gate_output_verdict_decoder())
  decode.success(GateOutput(
    verdict: field_verdict,
  ))
}

/// Generated from `schemas/gate_output.json` at `/properties/verdict`.
pub type GateOutputVerdict {
  GateOutputVerdict(
    outcome: GateOutputVerdictOutcome,
    report: option.Option(String),
  )
}

/// Encodes `GateOutputVerdict` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn gate_output_verdict_to_json(value: GateOutputVerdict) -> json.Json {
  json.object(
    list.flatten([
      [#("outcome", gate_output_verdict_outcome_to_json(value.outcome))],
      case value.report {
        option.Some(present) -> [#("report", json.string(present))]
        option.None -> []
      },
    ]),
  )
}

/// Decoder for `GateOutputVerdict` from schema-shaped JSON.
pub fn gate_output_verdict_decoder() -> decode.Decoder(GateOutputVerdict) {
  use field_outcome <- decode.field("outcome", gate_output_verdict_outcome_decoder())
  use field_report <- decode.optional_field(
    "report",
    option.None,
    decode.optional(decode.string),
  )
  decode.success(GateOutputVerdict(
    outcome: field_outcome,
    report: field_report,
  ))
}

/// Generated from `schemas/gate_output.json` at `/properties/verdict/properties/outcome`.
pub type GateOutputVerdictOutcome {
  GateOutputVerdictOutcomePass
  GateOutputVerdictOutcomeFail
}

/// Encodes `GateOutputVerdictOutcome` as its wire string.
pub fn gate_output_verdict_outcome_to_json(value: GateOutputVerdictOutcome) -> json.Json {
  case value {
    GateOutputVerdictOutcomePass -> json.string("pass")
    GateOutputVerdictOutcomeFail -> json.string("fail")
  }
}

/// Decoder for `GateOutputVerdictOutcome` from its wire string.
pub fn gate_output_verdict_outcome_decoder() -> decode.Decoder(GateOutputVerdictOutcome) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "pass" -> decode.success(GateOutputVerdictOutcomePass)
      "fail" -> decode.success(GateOutputVerdictOutcomeFail)
      _ -> decode.failure(GateOutputVerdictOutcomePass, "GateOutputVerdictOutcome")
    }
  })
}

/// Generated from `schemas/input.json`.
pub type Input {
  Input(
    repo_root: String,
    brief_id: String,
    reviewers: List(String),
    base_ref: String,
    placement: InputPlacement,
    isolation: InputIsolation,
    brief: String,
    design: String,
    checklist: String,
    stories: List(String),
    verify_fix_cap: Int,
    review_cap: Int,
    round_backoff_ms: Int,
    review_deadline_ms: Int,
  )
}

/// Encodes `Input` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn input_to_json(value: Input) -> json.Json {
  json.object([
    #("repo_root", json.string(value.repo_root)),
    #("brief_id", json.string(value.brief_id)),
    #("reviewers", json.array(value.reviewers, json.string)),
    #("base_ref", json.string(value.base_ref)),
    #("placement", input_placement_to_json(value.placement)),
    #("isolation", input_isolation_to_json(value.isolation)),
    #("brief", json.string(value.brief)),
    #("design", json.string(value.design)),
    #("checklist", json.string(value.checklist)),
    #("stories", json.array(value.stories, json.string)),
    #("verify_fix_cap", json.int(value.verify_fix_cap)),
    #("review_cap", json.int(value.review_cap)),
    #("round_backoff_ms", json.int(value.round_backoff_ms)),
    #("review_deadline_ms", json.int(value.review_deadline_ms)),
  ])
}

/// Decoder for `Input` from schema-shaped JSON.
pub fn input_decoder() -> decode.Decoder(Input) {
  use field_repo_root <- decode.field("repo_root", decode.string)
  use field_brief_id <- decode.field("brief_id", decode.string)
  use field_reviewers <- decode.field("reviewers", decode.list(decode.string))
  use field_base_ref <- decode.field("base_ref", decode.string)
  use field_placement <- decode.field("placement", input_placement_decoder())
  use field_isolation <- decode.field("isolation", input_isolation_decoder())
  use field_brief <- decode.field("brief", decode.string)
  use field_design <- decode.field("design", decode.string)
  use field_checklist <- decode.field("checklist", decode.string)
  use field_stories <- decode.field("stories", decode.list(decode.string))
  use field_verify_fix_cap <- decode.field("verify_fix_cap", decode.int)
  use field_review_cap <- decode.field("review_cap", decode.int)
  use field_round_backoff_ms <- decode.field("round_backoff_ms", decode.int)
  use field_review_deadline_ms <- decode.field("review_deadline_ms", decode.int)
  decode.success(Input(
    repo_root: field_repo_root,
    brief_id: field_brief_id,
    reviewers: field_reviewers,
    base_ref: field_base_ref,
    placement: field_placement,
    isolation: field_isolation,
    brief: field_brief,
    design: field_design,
    checklist: field_checklist,
    stories: field_stories,
    verify_fix_cap: field_verify_fix_cap,
    review_cap: field_review_cap,
    round_backoff_ms: field_round_backoff_ms,
    review_deadline_ms: field_review_deadline_ms,
  ))
}

/// Generated from `schemas/input.json` at `/properties/placement`.
pub type InputPlacement {
  InputPlacementLocal
  InputPlacementRemote
}

/// Encodes `InputPlacement` as its wire string.
pub fn input_placement_to_json(value: InputPlacement) -> json.Json {
  case value {
    InputPlacementLocal -> json.string("local")
    InputPlacementRemote -> json.string("remote")
  }
}

/// Decoder for `InputPlacement` from its wire string.
pub fn input_placement_decoder() -> decode.Decoder(InputPlacement) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "local" -> decode.success(InputPlacementLocal)
      "remote" -> decode.success(InputPlacementRemote)
      _ -> decode.failure(InputPlacementLocal, "InputPlacement")
    }
  })
}

/// Generated from `schemas/input.json` at `/properties/isolation`.
pub type InputIsolation {
  InputIsolationWorktree
  InputIsolationCopy
  InputIsolationOverlay
  InputIsolationVm
}

/// Encodes `InputIsolation` as its wire string.
pub fn input_isolation_to_json(value: InputIsolation) -> json.Json {
  case value {
    InputIsolationWorktree -> json.string("worktree")
    InputIsolationCopy -> json.string("copy")
    InputIsolationOverlay -> json.string("overlay")
    InputIsolationVm -> json.string("vm")
  }
}

/// Decoder for `InputIsolation` from its wire string.
pub fn input_isolation_decoder() -> decode.Decoder(InputIsolation) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "worktree" -> decode.success(InputIsolationWorktree)
      "copy" -> decode.success(InputIsolationCopy)
      "overlay" -> decode.success(InputIsolationOverlay)
      "vm" -> decode.success(InputIsolationVm)
      _ -> decode.failure(InputIsolationWorktree, "InputIsolation")
    }
  })
}

/// Generated from `schemas/onatopp_input.json`.
pub type OnatoppInput {
  OnatoppInput(
    workspace: OnatoppInputWorkspace,
    brief: String,
    design: String,
    checklist: String,
    stories: List(String),
    verify_fix_cap: Int,
    round_backoff_ms: Int,
  )
}

/// Encodes `OnatoppInput` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn onatopp_input_to_json(value: OnatoppInput) -> json.Json {
  json.object([
    #("workspace", onatopp_input_workspace_to_json(value.workspace)),
    #("brief", json.string(value.brief)),
    #("design", json.string(value.design)),
    #("checklist", json.string(value.checklist)),
    #("stories", json.array(value.stories, json.string)),
    #("verify_fix_cap", json.int(value.verify_fix_cap)),
    #("round_backoff_ms", json.int(value.round_backoff_ms)),
  ])
}

/// Decoder for `OnatoppInput` from schema-shaped JSON.
pub fn onatopp_input_decoder() -> decode.Decoder(OnatoppInput) {
  use field_workspace <- decode.field("workspace", onatopp_input_workspace_decoder())
  use field_brief <- decode.field("brief", decode.string)
  use field_design <- decode.field("design", decode.string)
  use field_checklist <- decode.field("checklist", decode.string)
  use field_stories <- decode.field("stories", decode.list(decode.string))
  use field_verify_fix_cap <- decode.field("verify_fix_cap", decode.int)
  use field_round_backoff_ms <- decode.field("round_backoff_ms", decode.int)
  decode.success(OnatoppInput(
    workspace: field_workspace,
    brief: field_brief,
    design: field_design,
    checklist: field_checklist,
    stories: field_stories,
    verify_fix_cap: field_verify_fix_cap,
    round_backoff_ms: field_round_backoff_ms,
  ))
}

/// Generated from `schemas/onatopp_input.json` at `/properties/workspace`.
pub type OnatoppInputWorkspace {
  OnatoppInputWorkspace(
    path: String,
    branch: String,
    placement: OnatoppInputWorkspacePlacement,
    isolation: OnatoppInputWorkspaceIsolation,
  )
}

/// Encodes `OnatoppInputWorkspace` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn onatopp_input_workspace_to_json(value: OnatoppInputWorkspace) -> json.Json {
  json.object([
    #("path", json.string(value.path)),
    #("branch", json.string(value.branch)),
    #("placement", onatopp_input_workspace_placement_to_json(value.placement)),
    #("isolation", onatopp_input_workspace_isolation_to_json(value.isolation)),
  ])
}

/// Decoder for `OnatoppInputWorkspace` from schema-shaped JSON.
pub fn onatopp_input_workspace_decoder() -> decode.Decoder(OnatoppInputWorkspace) {
  use field_path <- decode.field("path", decode.string)
  use field_branch <- decode.field("branch", decode.string)
  use field_placement <- decode.field("placement", onatopp_input_workspace_placement_decoder())
  use field_isolation <- decode.field("isolation", onatopp_input_workspace_isolation_decoder())
  decode.success(OnatoppInputWorkspace(
    path: field_path,
    branch: field_branch,
    placement: field_placement,
    isolation: field_isolation,
  ))
}

/// Generated from `schemas/onatopp_input.json` at `/properties/workspace/properties/placement`.
pub type OnatoppInputWorkspacePlacement {
  OnatoppInputWorkspacePlacementLocal
  OnatoppInputWorkspacePlacementRemote
}

/// Encodes `OnatoppInputWorkspacePlacement` as its wire string.
pub fn onatopp_input_workspace_placement_to_json(value: OnatoppInputWorkspacePlacement) -> json.Json {
  case value {
    OnatoppInputWorkspacePlacementLocal -> json.string("local")
    OnatoppInputWorkspacePlacementRemote -> json.string("remote")
  }
}

/// Decoder for `OnatoppInputWorkspacePlacement` from its wire string.
pub fn onatopp_input_workspace_placement_decoder() -> decode.Decoder(OnatoppInputWorkspacePlacement) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "local" -> decode.success(OnatoppInputWorkspacePlacementLocal)
      "remote" -> decode.success(OnatoppInputWorkspacePlacementRemote)
      _ -> decode.failure(OnatoppInputWorkspacePlacementLocal, "OnatoppInputWorkspacePlacement")
    }
  })
}

/// Generated from `schemas/onatopp_input.json` at `/properties/workspace/properties/isolation`.
pub type OnatoppInputWorkspaceIsolation {
  OnatoppInputWorkspaceIsolationWorktree
  OnatoppInputWorkspaceIsolationCopy
  OnatoppInputWorkspaceIsolationOverlay
  OnatoppInputWorkspaceIsolationVm
}

/// Encodes `OnatoppInputWorkspaceIsolation` as its wire string.
pub fn onatopp_input_workspace_isolation_to_json(value: OnatoppInputWorkspaceIsolation) -> json.Json {
  case value {
    OnatoppInputWorkspaceIsolationWorktree -> json.string("worktree")
    OnatoppInputWorkspaceIsolationCopy -> json.string("copy")
    OnatoppInputWorkspaceIsolationOverlay -> json.string("overlay")
    OnatoppInputWorkspaceIsolationVm -> json.string("vm")
  }
}

/// Decoder for `OnatoppInputWorkspaceIsolation` from its wire string.
pub fn onatopp_input_workspace_isolation_decoder() -> decode.Decoder(OnatoppInputWorkspaceIsolation) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "worktree" -> decode.success(OnatoppInputWorkspaceIsolationWorktree)
      "copy" -> decode.success(OnatoppInputWorkspaceIsolationCopy)
      "overlay" -> decode.success(OnatoppInputWorkspaceIsolationOverlay)
      "vm" -> decode.success(OnatoppInputWorkspaceIsolationVm)
      _ -> decode.failure(OnatoppInputWorkspaceIsolationWorktree, "OnatoppInputWorkspaceIsolation")
    }
  })
}

/// Generated from `schemas/onatopp_output.json`.
pub type OnatoppOutput {
  OnatoppOutput(
    dev_result: OnatoppOutputDevResult,
    build_warm: OnatoppOutputBuildWarm,
    verify_rounds: Int,
  )
}

/// Encodes `OnatoppOutput` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn onatopp_output_to_json(value: OnatoppOutput) -> json.Json {
  json.object([
    #("dev_result", onatopp_output_dev_result_to_json(value.dev_result)),
    #("build_warm", onatopp_output_build_warm_to_json(value.build_warm)),
    #("verify_rounds", json.int(value.verify_rounds)),
  ])
}

/// Decoder for `OnatoppOutput` from schema-shaped JSON.
pub fn onatopp_output_decoder() -> decode.Decoder(OnatoppOutput) {
  use field_dev_result <- decode.field("dev_result", onatopp_output_dev_result_decoder())
  use field_build_warm <- decode.field("build_warm", onatopp_output_build_warm_decoder())
  use field_verify_rounds <- decode.field("verify_rounds", decode.int)
  decode.success(OnatoppOutput(
    dev_result: field_dev_result,
    build_warm: field_build_warm,
    verify_rounds: field_verify_rounds,
  ))
}

/// Generated from `schemas/onatopp_output.json` at `/properties/dev_result`.
pub type OnatoppOutputDevResult {
  OnatoppOutputDevResult(
    session_id: String,
    files_touched: List(String),
    summary: String,
  )
}

/// Encodes `OnatoppOutputDevResult` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn onatopp_output_dev_result_to_json(value: OnatoppOutputDevResult) -> json.Json {
  json.object([
    #("session_id", json.string(value.session_id)),
    #("files_touched", json.array(value.files_touched, json.string)),
    #("summary", json.string(value.summary)),
  ])
}

/// Decoder for `OnatoppOutputDevResult` from schema-shaped JSON.
pub fn onatopp_output_dev_result_decoder() -> decode.Decoder(OnatoppOutputDevResult) {
  use field_session_id <- decode.field("session_id", decode.string)
  use field_files_touched <- decode.field("files_touched", decode.list(decode.string))
  use field_summary <- decode.field("summary", decode.string)
  decode.success(OnatoppOutputDevResult(
    session_id: field_session_id,
    files_touched: field_files_touched,
    summary: field_summary,
  ))
}

/// Generated from `schemas/onatopp_output.json` at `/properties/build_warm`.
pub type OnatoppOutputBuildWarm {
  OnatoppOutputBuildWarm(
    ok: Bool,
    duration_ms: Int,
  )
}

/// Encodes `OnatoppOutputBuildWarm` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn onatopp_output_build_warm_to_json(value: OnatoppOutputBuildWarm) -> json.Json {
  json.object([
    #("ok", json.bool(value.ok)),
    #("duration_ms", json.int(value.duration_ms)),
  ])
}

/// Decoder for `OnatoppOutputBuildWarm` from schema-shaped JSON.
pub fn onatopp_output_build_warm_decoder() -> decode.Decoder(OnatoppOutputBuildWarm) {
  use field_ok <- decode.field("ok", decode.bool)
  use field_duration_ms <- decode.field("duration_ms", decode.int)
  decode.success(OnatoppOutputBuildWarm(
    ok: field_ok,
    duration_ms: field_duration_ms,
  ))
}

/// Generated from `schemas/output.json`.
pub type Output {
  Output(
    branch: String,
    merged_into: String,
    session_id: String,
    build_warm: OutputBuildWarm,
    verify_rounds: Int,
    review_rounds: Int,
  )
}

/// Encodes `Output` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn output_to_json(value: Output) -> json.Json {
  json.object([
    #("branch", json.string(value.branch)),
    #("merged_into", json.string(value.merged_into)),
    #("session_id", json.string(value.session_id)),
    #("build_warm", output_build_warm_to_json(value.build_warm)),
    #("verify_rounds", json.int(value.verify_rounds)),
    #("review_rounds", json.int(value.review_rounds)),
  ])
}

/// Decoder for `Output` from schema-shaped JSON.
pub fn output_decoder() -> decode.Decoder(Output) {
  use field_branch <- decode.field("branch", decode.string)
  use field_merged_into <- decode.field("merged_into", decode.string)
  use field_session_id <- decode.field("session_id", decode.string)
  use field_build_warm <- decode.field("build_warm", output_build_warm_decoder())
  use field_verify_rounds <- decode.field("verify_rounds", decode.int)
  use field_review_rounds <- decode.field("review_rounds", decode.int)
  decode.success(Output(
    branch: field_branch,
    merged_into: field_merged_into,
    session_id: field_session_id,
    build_warm: field_build_warm,
    verify_rounds: field_verify_rounds,
    review_rounds: field_review_rounds,
  ))
}

/// Generated from `schemas/output.json` at `/properties/build_warm`.
pub type OutputBuildWarm {
  OutputBuildWarm(
    ok: Bool,
    duration_ms: Int,
  )
}

/// Encodes `OutputBuildWarm` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn output_build_warm_to_json(value: OutputBuildWarm) -> json.Json {
  json.object([
    #("ok", json.bool(value.ok)),
    #("duration_ms", json.int(value.duration_ms)),
  ])
}

/// Decoder for `OutputBuildWarm` from schema-shaped JSON.
pub fn output_build_warm_decoder() -> decode.Decoder(OutputBuildWarm) {
  use field_ok <- decode.field("ok", decode.bool)
  use field_duration_ms <- decode.field("duration_ms", decode.int)
  decode.success(OutputBuildWarm(
    ok: field_ok,
    duration_ms: field_duration_ms,
  ))
}

/// Generated from `schemas/review_report.json`.
pub type ReviewReport {
  ReviewReport(
    summary: String,
    commit_message: String,
    enrichments: List(ReviewReportEnrichmentsItem),
    verification: List(ReviewReportVerificationItem),
  )
}

/// Encodes `ReviewReport` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn review_report_to_json(value: ReviewReport) -> json.Json {
  json.object([
    #("summary", json.string(value.summary)),
    #("commit_message", json.string(value.commit_message)),
    #("enrichments", json.array(value.enrichments, review_report_enrichments_item_to_json)),
    #("verification", json.array(value.verification, review_report_verification_item_to_json)),
  ])
}

/// Decoder for `ReviewReport` from schema-shaped JSON.
pub fn review_report_decoder() -> decode.Decoder(ReviewReport) {
  use field_summary <- decode.field("summary", decode.string)
  use field_commit_message <- decode.field("commit_message", decode.string)
  use field_enrichments <- decode.field("enrichments", decode.list(review_report_enrichments_item_decoder()))
  use field_verification <- decode.field("verification", decode.list(review_report_verification_item_decoder()))
  decode.success(ReviewReport(
    summary: field_summary,
    commit_message: field_commit_message,
    enrichments: field_enrichments,
    verification: field_verification,
  ))
}

/// Generated from `schemas/review_report.json` at `/properties/enrichments/items`.
pub type ReviewReportEnrichmentsItem {
  ReviewReportEnrichmentsItem(
    id: String,
    alignment: ReviewReportEnrichmentsItemAlignment,
    acceptance: List(ReviewReportEnrichmentsItemAcceptanceItem),
    checklist: List(String),
    stories: List(String),
    issues: List(String),
    fixes: List(String),
  )
}

/// Encodes `ReviewReportEnrichmentsItem` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn review_report_enrichments_item_to_json(value: ReviewReportEnrichmentsItem) -> json.Json {
  json.object([
    #("id", json.string(value.id)),
    #("alignment", review_report_enrichments_item_alignment_to_json(value.alignment)),
    #("acceptance", json.array(value.acceptance, review_report_enrichments_item_acceptance_item_to_json)),
    #("checklist", json.array(value.checklist, json.string)),
    #("stories", json.array(value.stories, json.string)),
    #("issues", json.array(value.issues, json.string)),
    #("fixes", json.array(value.fixes, json.string)),
  ])
}

/// Decoder for `ReviewReportEnrichmentsItem` from schema-shaped JSON.
pub fn review_report_enrichments_item_decoder() -> decode.Decoder(ReviewReportEnrichmentsItem) {
  use field_id <- decode.field("id", decode.string)
  use field_alignment <- decode.field("alignment", review_report_enrichments_item_alignment_decoder())
  use field_acceptance <- decode.field("acceptance", decode.list(review_report_enrichments_item_acceptance_item_decoder()))
  use field_checklist <- decode.field("checklist", decode.list(decode.string))
  use field_stories <- decode.field("stories", decode.list(decode.string))
  use field_issues <- decode.field("issues", decode.list(decode.string))
  use field_fixes <- decode.field("fixes", decode.list(decode.string))
  decode.success(ReviewReportEnrichmentsItem(
    id: field_id,
    alignment: field_alignment,
    acceptance: field_acceptance,
    checklist: field_checklist,
    stories: field_stories,
    issues: field_issues,
    fixes: field_fixes,
  ))
}

/// Generated from `schemas/review_report.json` at `/properties/enrichments/items/properties/alignment`.
pub type ReviewReportEnrichmentsItemAlignment {
  ReviewReportEnrichmentsItemAlignmentAligned
  ReviewReportEnrichmentsItemAlignmentDrifted
  ReviewReportEnrichmentsItemAlignmentFixed
}

/// Encodes `ReviewReportEnrichmentsItemAlignment` as its wire string.
pub fn review_report_enrichments_item_alignment_to_json(value: ReviewReportEnrichmentsItemAlignment) -> json.Json {
  case value {
    ReviewReportEnrichmentsItemAlignmentAligned -> json.string("aligned")
    ReviewReportEnrichmentsItemAlignmentDrifted -> json.string("drifted")
    ReviewReportEnrichmentsItemAlignmentFixed -> json.string("fixed")
  }
}

/// Decoder for `ReviewReportEnrichmentsItemAlignment` from its wire string.
pub fn review_report_enrichments_item_alignment_decoder() -> decode.Decoder(ReviewReportEnrichmentsItemAlignment) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "aligned" -> decode.success(ReviewReportEnrichmentsItemAlignmentAligned)
      "drifted" -> decode.success(ReviewReportEnrichmentsItemAlignmentDrifted)
      "fixed" -> decode.success(ReviewReportEnrichmentsItemAlignmentFixed)
      _ -> decode.failure(ReviewReportEnrichmentsItemAlignmentAligned, "ReviewReportEnrichmentsItemAlignment")
    }
  })
}

/// Generated from `schemas/review_report.json` at `/properties/enrichments/items/properties/acceptance/items`.
pub type ReviewReportEnrichmentsItemAcceptanceItem {
  ReviewReportEnrichmentsItemAcceptanceItem(
    criterion: String,
    met: Bool,
    evidence: String,
  )
}

/// Encodes `ReviewReportEnrichmentsItemAcceptanceItem` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn review_report_enrichments_item_acceptance_item_to_json(value: ReviewReportEnrichmentsItemAcceptanceItem) -> json.Json {
  json.object([
    #("criterion", json.string(value.criterion)),
    #("met", json.bool(value.met)),
    #("evidence", json.string(value.evidence)),
  ])
}

/// Decoder for `ReviewReportEnrichmentsItemAcceptanceItem` from schema-shaped JSON.
pub fn review_report_enrichments_item_acceptance_item_decoder() -> decode.Decoder(ReviewReportEnrichmentsItemAcceptanceItem) {
  use field_criterion <- decode.field("criterion", decode.string)
  use field_met <- decode.field("met", decode.bool)
  use field_evidence <- decode.field("evidence", decode.string)
  decode.success(ReviewReportEnrichmentsItemAcceptanceItem(
    criterion: field_criterion,
    met: field_met,
    evidence: field_evidence,
  ))
}

/// Generated from `schemas/review_report.json` at `/properties/verification/items`.
pub type ReviewReportVerificationItem {
  ReviewReportVerificationItem(
    criterion: String,
    passed: Bool,
    note: String,
  )
}

/// Encodes `ReviewReportVerificationItem` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn review_report_verification_item_to_json(value: ReviewReportVerificationItem) -> json.Json {
  json.object([
    #("criterion", json.string(value.criterion)),
    #("passed", json.bool(value.passed)),
    #("note", json.string(value.note)),
  ])
}

/// Decoder for `ReviewReportVerificationItem` from schema-shaped JSON.
pub fn review_report_verification_item_decoder() -> decode.Decoder(ReviewReportVerificationItem) {
  use field_criterion <- decode.field("criterion", decode.string)
  use field_passed <- decode.field("passed", decode.bool)
  use field_note <- decode.field("note", decode.string)
  decode.success(ReviewReportVerificationItem(
    criterion: field_criterion,
    passed: field_passed,
    note: field_note,
  ))
}

/// Generated from `schemas/scout_report.json`.
pub type ScoutReport {
  ScoutReport(
    summary: String,
    enrichments: List(ScoutReportEnrichmentsItem),
    verification: List(String),
  )
}

/// Encodes `ScoutReport` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn scout_report_to_json(value: ScoutReport) -> json.Json {
  json.object([
    #("summary", json.string(value.summary)),
    #("enrichments", json.array(value.enrichments, scout_report_enrichments_item_to_json)),
    #("verification", json.array(value.verification, json.string)),
  ])
}

/// Decoder for `ScoutReport` from schema-shaped JSON.
pub fn scout_report_decoder() -> decode.Decoder(ScoutReport) {
  use field_summary <- decode.field("summary", decode.string)
  use field_enrichments <- decode.field("enrichments", decode.list(scout_report_enrichments_item_decoder()))
  use field_verification <- decode.field("verification", decode.list(decode.string))
  decode.success(ScoutReport(
    summary: field_summary,
    enrichments: field_enrichments,
    verification: field_verification,
  ))
}

/// Generated from `schemas/scout_report.json` at `/properties/enrichments/items`.
pub type ScoutReportEnrichmentsItem {
  ScoutReportEnrichmentsItem(
    id: String,
    files: List(String),
    context: List(String),
    approach: String,
    notes: String,
  )
}

/// Encodes `ScoutReportEnrichmentsItem` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn scout_report_enrichments_item_to_json(value: ScoutReportEnrichmentsItem) -> json.Json {
  json.object([
    #("id", json.string(value.id)),
    #("files", json.array(value.files, json.string)),
    #("context", json.array(value.context, json.string)),
    #("approach", json.string(value.approach)),
    #("notes", json.string(value.notes)),
  ])
}

/// Decoder for `ScoutReportEnrichmentsItem` from schema-shaped JSON.
pub fn scout_report_enrichments_item_decoder() -> decode.Decoder(ScoutReportEnrichmentsItem) {
  use field_id <- decode.field("id", decode.string)
  use field_files <- decode.field("files", decode.list(decode.string))
  use field_context <- decode.field("context", decode.list(decode.string))
  use field_approach <- decode.field("approach", decode.string)
  use field_notes <- decode.field("notes", decode.string)
  decode.success(ScoutReportEnrichmentsItem(
    id: field_id,
    files: field_files,
    context: field_context,
    approach: field_approach,
    notes: field_notes,
  ))
}
