//! Access to the embedded SDK/stdlib BEAM closure.
//!
//! Direct-compiled AWL workflow BEAM imports `aion_flow` SDK and Gleam
//! stdlib modules; this closure ships those modules prebuilt, embedded in
//! the compiled binary, so the product path never invokes a Gleam
//! toolchain. The bytes live in [`super::bundle_data`], a committed file
//! generated by `scripts/regen-awl-sdk-closure.sh` (a dev-time step that
//! requires a local `gleam`; no build.rs or product path calls it).

use super::bundle_data;

/// Returns the `aion_flow` SDK version the embedded closure was built from.
#[must_use]
pub fn sdk_closure_version() -> &'static str {
    bundle_data::SDK_CLOSURE_VERSION
}

/// Iterates the embedded closure as `(logical module name, .beam bytes)`
/// pairs, sorted by module name.
pub fn sdk_closure_modules() -> impl Iterator<Item = (&'static str, &'static [u8])> {
    bundle_data::MODULES
        .iter()
        .map(|(name, bytes)| (*name, *bytes))
}

/// Returns true when the closure ships a module with this logical name.
pub(crate) fn contains(name: &str) -> bool {
    bundle_data::MODULES
        .binary_search_by(|(module, _)| (*module).cmp(name))
        .is_ok()
}

#[cfg(test)]
mod tests {
    use super::{contains, sdk_closure_modules, sdk_closure_version};

    /// `contains` binary-searches, so the generated table must stay sorted
    /// and duplicate-free.
    #[test]
    fn generated_table_is_sorted_and_duplicate_free() {
        let names: Vec<&str> = sdk_closure_modules().map(|(name, _)| name).collect();
        let mut sorted = names.clone();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(names, sorted);
    }

    #[test]
    fn closure_is_nonempty_and_versioned() {
        assert!(sdk_closure_modules().count() > 0);
        assert!(!sdk_closure_version().is_empty());
        assert!(contains("aion@workflow"));
        assert!(!contains("no_such_module"));
    }
}
