# Generated by aion generate — do not edit; regenerate from the activity declarations.
"""aion_order_saga Aion worker.

Serves the package's RemotePython activities against a running Aion server.
The activity bodies live in `handlers.py`; this module is generated plumbing.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
from collections.abc import Awaitable, Callable, Iterable

from aion_worker import (
    ActivityExecutionContext,
    ActivityTask,
    DispatchOutcome,
    Failed,
    GrpcWorkerSession,
    ReconnectConfig,
    WorkerConfig,
    connect_register_replay_and_serve,
)
from aion_worker.proto import common_pb2, worker_pb2

import handlers

JSON_CONTENT_TYPE = "application/json"
Handler = Callable[[dict[str, object]], Awaitable[DispatchOutcome]]


class AionOrderSagaDispatcher:
    """Routes the aion_order_saga activities to their handlers."""

    def __init__(self) -> None:
        self._handlers: dict[str, Handler] = {
            "reserve_inventory": handlers.reserve_inventory,
            "charge_payment": handlers.charge_payment,
            "ship_order": handlers.ship_order,
            "release_inventory": handlers.release_inventory,
            "refund_payment": handlers.refund_payment,
            "cancel_shipment": handlers.cancel_shipment,
        }

    def activity_types(self) -> Iterable[str]:
        return self._handlers.keys()

    async def dispatch(
        self, task: ActivityTask, context: ActivityExecutionContext
    ) -> DispatchOutcome:
        del context
        handler = self._handlers.get(task.activity_type)
        if handler is None:
            return worker_failure(f"unknown activity type: {task.activity_type}")
        try:
            request = decode_json_object(task.input)
            return await handler(request)
        except (KeyError, ValueError, json.JSONDecodeError, UnicodeDecodeError) as exc:
            return worker_failure(str(exc))


def decode_json_object(payload: common_pb2.Payload) -> dict[str, object]:
    if payload.content_type != JSON_CONTENT_TYPE:
        raise ValueError(f"expected {JSON_CONTENT_TYPE} payload, got {payload.content_type!r}")
    value = json.loads(payload.bytes.decode("utf-8"))
    if not isinstance(value, dict):
        raise ValueError("expected JSON object input")
    return value


def worker_failure(message: str) -> DispatchOutcome:
    return Failed(
        worker_pb2.ActivityError(
            kind=worker_pb2.ACTIVITY_ERROR_KIND_TERMINAL,
            message=message,
        )
    )


def worker_config() -> WorkerConfig:
    return WorkerConfig(
        endpoint=os.environ.get("AION_WORKER_ENDPOINT", "127.0.0.1:50051"),
        task_queue=os.environ.get("AION_TASK_QUEUE", "default"),
        identity=os.environ.get("AION_WORKER_IDENTITY", "aion_order_saga-python-worker"),
        max_concurrency=int(os.environ.get("AION_WORKER_CONCURRENCY", "4")),
        reconnect=ReconnectConfig(
            initial_backoff_seconds=float(os.environ.get("AION_RECONNECT_INITIAL_BACKOFF_SECONDS", "0.5")),
            max_backoff_seconds=float(os.environ.get("AION_RECONNECT_MAX_BACKOFF_SECONDS", "5.0")),
            max_attempts=int(os.environ.get("AION_RECONNECT_MAX_ATTEMPTS", "10")),
        ),
        namespace=os.environ.get("AION_NAMESPACE", "default"),
        subject=os.environ.get("AION_SUBJECT", "worker"),
    )


async def main() -> None:
    logging.basicConfig(level=logging.INFO)
    config = worker_config()
    dispatcher = AionOrderSagaDispatcher()
    await connect_register_replay_and_serve(
        config=config,
        connect=lambda: GrpcWorkerSession.connect(config),
        dispatcher=dispatcher,
    )


if __name__ == "__main__":
    asyncio.run(main())
