//! TypeScript export tests for the ops console generated-types pipeline.

use std::fs;
use std::path::PathBuf;

use ts_rs::{Config, TS};

use crate::{
    ActivityError, ActivityErrorKind, ActivityEvent, ActivityEventKind, ActivityId,
    ApprovalDecision, CatchUpPolicy, ClusterCommand, ClusterEvent, ClusterEventMeta, ClusterPeer,
    ClusterShard, ClusterSnapshot, ClusterStreamError, ClusterWorker, ContentType,
    DescribeWorkflowResponse, Event, EventEnvelope, InjectPriority, InterventionCapabilities,
    InterventionCommand, InterventionKind, InterventionOutcome, InterventionPrimitive, MessageRole,
    NamespacePlacementWire, OverlapPolicy, PackageVersion, Payload, ProgressDetail, RunId,
    ScheduleConfig, ScheduleId, SearchAttributeType, SearchAttributeValue, StopKind, TimerId,
    TimerIdKind, TriggerSpec, WithTimeoutOutcome, WorkerDeathReason, WorkerTransport,
    WorkflowError, WorkflowFilter, WorkflowId, WorkflowStatus, WorkflowSummary,
};

const OPS_CONSOLE_GENERATED_DIR: &str = "../../apps/aion-ops-console/src/types/generated";
const GENERATED_HEADER: &str = concat!(
    "// This file is @generated by the aion-core/aion-proto ts-rs generated-types pipeline.\n",
    "// Do not edit by hand. Regenerate with the command documented in ",
    "apps/aion-ops-console/README.md.\n\n",
);
const TS_RS_HEADER: &str = concat!(
    "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). ",
    "Do not edit this file manually.\n\n",
);

#[test]
fn export_ops_console_wire_types() -> Result<(), Box<dyn std::error::Error>> {
    let generated = ops_console_wire_types()?;
    let output_path = ops_console_generated_index_path();

    fs::write(output_path, generated)?;

    Ok(())
}

fn ops_console_wire_types() -> Result<String, ts_rs::ExportError> {
    let config = Config::new().with_out_dir(".").with_large_int("number");
    let mut output = String::from(GENERATED_HEADER);

    push_type::<WorkflowId>(&config, &mut output)?;
    push_type::<RunId>(&config, &mut output)?;
    push_type::<PackageVersion>(&config, &mut output)?;
    push_type::<ScheduleId>(&config, &mut output)?;
    push_type::<ActivityId>(&config, &mut output)?;
    push_type::<TimerIdKind>(&config, &mut output)?;
    push_type::<TimerId>(&config, &mut output)?;
    output.push_str("export type Namespace = string;\n\n");
    push_type::<ContentType>(&config, &mut output)?;
    push_type::<Payload>(&config, &mut output)?;
    push_type::<TriggerSpec>(&config, &mut output)?;
    push_type::<OverlapPolicy>(&config, &mut output)?;
    push_type::<CatchUpPolicy>(&config, &mut output)?;
    push_type::<ScheduleConfig>(&config, &mut output)?;
    push_type::<WorkflowError>(&config, &mut output)?;
    push_type::<ActivityErrorKind>(&config, &mut output)?;
    push_type::<ActivityError>(&config, &mut output)?;
    push_type::<WorkflowStatus>(&config, &mut output)?;
    push_type::<WorkflowFilter>(&config, &mut output)?;
    push_type::<WorkflowSummary>(&config, &mut output)?;
    push_type::<SearchAttributeType>(&config, &mut output)?;
    push_type::<SearchAttributeValue>(&config, &mut output)?;
    push_type::<EventEnvelope>(&config, &mut output)?;
    push_type::<WithTimeoutOutcome>(&config, &mut output)?;
    push_type::<Event>(&config, &mut output)?;
    push_type::<DescribeWorkflowResponse>(&config, &mut output)?;

    // WS3 cluster real-time channel wire types. The aion-proto frame envelopes
    // (StreamedClusterEvent etc.) are intentionally NOT exported here — like StreamedEvent on the
    // workflow path, the outer frame wrappers are hand-decoded on the TS side; only these inner
    // aion-core payload types cross the ts-rs boundary.
    push_type::<ClusterEventMeta>(&config, &mut output)?;
    push_type::<WorkerTransport>(&config, &mut output)?;
    push_type::<WorkerDeathReason>(&config, &mut output)?;
    push_type::<NamespacePlacementWire>(&config, &mut output)?;
    push_type::<ClusterEvent>(&config, &mut output)?;
    push_type::<ClusterPeer>(&config, &mut output)?;
    push_type::<ClusterShard>(&config, &mut output)?;
    push_type::<ClusterWorker>(&config, &mut output)?;
    push_type::<ClusterSnapshot>(&config, &mut output)?;
    push_type::<ClusterCommand>(&config, &mut output)?;
    push_type::<ClusterStreamError>(&config, &mut output)?;

    // Agent-observability + intervention real-time channel wire types. Like the cluster
    // channel, only these inner aion-core payload types cross the ts-rs boundary; any outer
    // frame envelopes are hand-decoded on the TS side.
    push_type::<MessageRole>(&config, &mut output)?;
    push_type::<ProgressDetail>(&config, &mut output)?;
    push_type::<StopKind>(&config, &mut output)?;
    push_type::<ActivityEventKind>(&config, &mut output)?;
    push_type::<ActivityEvent>(&config, &mut output)?;
    push_type::<InjectPriority>(&config, &mut output)?;
    push_type::<ApprovalDecision>(&config, &mut output)?;
    push_type::<InterventionPrimitive>(&config, &mut output)?;
    push_type::<InterventionKind>(&config, &mut output)?;
    push_type::<InterventionCommand>(&config, &mut output)?;
    push_type::<InterventionCapabilities>(&config, &mut output)?;
    push_type::<InterventionOutcome>(&config, &mut output)?;

    Ok(output)
}

fn push_type<T>(config: &Config, output: &mut String) -> Result<(), ts_rs::ExportError>
where
    T: TS + 'static,
{
    let declaration = T::export_to_string(config)?;
    output.push_str(strip_ts_rs_prelude(&declaration));
    output.push('\n');
    Ok(())
}

fn strip_ts_rs_prelude(declaration: &str) -> &str {
    let without_header = declaration
        .strip_prefix(TS_RS_HEADER)
        .unwrap_or(declaration);

    without_header
        .find("\nexport ")
        .map_or(without_header, |export_start| {
            &without_header[export_start + 1..]
        })
}

fn ops_console_generated_index_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join(OPS_CONSOLE_GENERATED_DIR)
        .join("index.ts")
}
