#!/usr/bin/env python3
"""Simulated AI-agent worker for the Aion agent-orchestration example.

Run this after the Aion server is listening on gRPC localhost:50051. The worker
registers `develop` and `review` activities. The handlers are intentionally
simulated: `develop` fabricates a plausible diff and commit message, while
`review` asks for one revision on attempt 1 and lands on attempt 2.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
from collections.abc import Iterable
from typing import Any

from aion_worker import (
    ActivityExecutionContext,
    ActivityTask,
    Completed,
    DispatchOutcome,
    Failed,
    GrpcWorkerSession,
    ReconnectConfig,
    WorkerConfig,
    connect_register_replay_and_serve,
)
from aion_worker.proto import common_pb2, worker_pb2

JSON_CONTENT_TYPE = "application/json"


class AgentOrchestrationDispatcher:
    """Dispatcher for simulated `develop` and `review` AI-agent activities."""

    def activity_types(self) -> Iterable[str]:
        return ["develop", "review"]

    async def dispatch(self, task: ActivityTask, context: ActivityExecutionContext) -> DispatchOutcome:
        del context
        try:
            request = decode_json_object(task.input)
            if task.activity_type == "develop":
                return Completed(json_payload(develop(request)))
            if task.activity_type == "review":
                return Completed(json_payload(review(request)))
            return worker_failure(f"unknown activity type: {task.activity_type}")
        except (KeyError, TypeError, ValueError, json.JSONDecodeError, UnicodeDecodeError) as exc:
            return worker_failure(str(exc))


def develop(request: dict[str, Any]) -> dict[str, str]:
    brief = object_field(request, "brief")
    title = string_field(brief, "title")
    requirements = string_list_field(brief, "requirements")
    revision_findings = string_list_field(request, "revision_findings")
    attempt = int_field(request, "attempt")

    logging.info("develop attempt %s started for %r", attempt, title)
    if revision_findings:
        logging.info("develop attempt %s applying reviewer findings: %s", attempt, revision_findings)

    requirement_lines = "\n".join(f"+  - {requirement}" for requirement in requirements)
    findings_lines = "\n".join(f"+  - addressed review: {finding}" for finding in revision_findings)
    code_diff = (
        "diff --git a/AGENT_PIPELINE.md b/AGENT_PIPELINE.md\n"
        "new file mode 100644\n"
        "--- /dev/null\n"
        "+++ b/AGENT_PIPELINE.md\n"
        "@@\n"
        f"+# {title}\n"
        f"+Generated by simulated dev agent on attempt {attempt}.\n"
        "+\n"
        "+## Requirements implemented\n"
        f"{requirement_lines}\n"
    )
    if findings_lines:
        code_diff += "+\n+## Review feedback addressed\n" + findings_lines + "\n"

    output = {
        "code_diff": code_diff,
        "commit_message": f"feat: {slug_commit_subject(title)}",
    }
    logging.info("develop attempt %s completed with commit message %r", attempt, output["commit_message"])
    return output


def review(request: dict[str, Any]) -> dict[str, object]:
    brief = object_field(request, "brief")
    title = string_field(brief, "title")
    dev_output = object_field(request, "dev_output")
    commit_message = string_field(dev_output, "commit_message")
    attempt = int_field(request, "attempt")

    logging.info("review attempt %s started for %r (%s)", attempt, title, commit_message)
    if attempt == 1:
        finding = "Document the durability/replay behavior so operators know the dev result is cached."
        logging.info("review attempt %s verdict=revise finding=%r", attempt, finding)
        return {"verdict": "revise", "findings": [finding]}

    logging.info("review attempt %s verdict=land", attempt)
    return {"verdict": "land", "findings": []}


def decode_json_object(payload: common_pb2.Payload) -> dict[str, Any]:
    if payload.content_type != JSON_CONTENT_TYPE:
        raise ValueError(f"expected {JSON_CONTENT_TYPE} payload, got {payload.content_type!r}")
    value = json.loads(payload.bytes.decode("utf-8"))
    if not isinstance(value, dict):
        raise ValueError("expected JSON object input")
    return value


def json_payload(value: object) -> common_pb2.Payload:
    return common_pb2.Payload(
        content_type=JSON_CONTENT_TYPE,
        bytes=json.dumps(value, separators=(",", ":")).encode("utf-8"),
    )


def object_field(value: dict[str, Any], name: str) -> dict[str, Any]:
    field = value[name]
    if not isinstance(field, dict):
        raise ValueError(f"expected object field {name!r}")
    return field


def string_field(value: dict[str, Any], name: str) -> str:
    field = value[name]
    if not isinstance(field, str) or not field:
        raise ValueError(f"expected non-empty string field {name!r}")
    return field


def string_list_field(value: dict[str, Any], name: str) -> list[str]:
    field = value[name]
    if not isinstance(field, list) or not all(isinstance(item, str) for item in field):
        raise ValueError(f"expected string list field {name!r}")
    return field


def int_field(value: dict[str, Any], name: str) -> int:
    field = value[name]
    if not isinstance(field, int):
        raise ValueError(f"expected integer field {name!r}")
    return field


def slug_commit_subject(title: str) -> str:
    return " ".join(title.strip().lower().split())


def worker_failure(message: str) -> DispatchOutcome:
    logging.error("activity failed: %s", message)
    return Failed(
        worker_pb2.ActivityError(
            kind=worker_pb2.ACTIVITY_ERROR_KIND_TERMINAL,
            message=message,
        )
    )


def worker_config() -> WorkerConfig:
    return WorkerConfig(
        endpoint=os.environ.get("AION_WORKER_ENDPOINT", "127.0.0.1:50051"),
        task_queue=os.environ.get("AION_TASK_QUEUE", "default"),
        identity=os.environ.get("AION_WORKER_IDENTITY", "agent-orchestration-python-worker"),
        max_concurrency=int(os.environ.get("AION_WORKER_CONCURRENCY", "4")),
        reconnect=ReconnectConfig(
            initial_backoff_seconds=0.5,
            max_backoff_seconds=5.0,
            max_attempts=10,
        ),
    )


async def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    config = worker_config()
    dispatcher = AgentOrchestrationDispatcher()
    logging.info("serving simulated develop/review activities on %s", config.endpoint)
    await connect_register_replay_and_serve(
        config=config,
        connect=lambda: GrpcWorkerSession.connect(config),
        dispatcher=dispatcher,
    )


if __name__ == "__main__":
    asyncio.run(main())
