//// Generated by aion generate — do not edit; regenerate from the project's types module.
////
//// JSON codecs for the `agent_dev` boundary types declared in
//// `src/agent_dev_io.gleam`: per type, a schema-shaped encoder/decoder
//// pair and a typed codec for activity and workflow I/O.

import aion/codec
import gleam/dynamic/decode
import gleam/json
import agent_dev_io as io

/// Encodes `io.AgentDevError` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn agent_dev_error_to_json(value: io.AgentDevError) -> json.Json {
  json.object([
    #("stage", json.string(value.stage)),
    #("message", json.string(value.message)),
  ])
}

/// Decoder for `io.AgentDevError` from schema-shaped JSON.
pub fn agent_dev_error_decoder() -> decode.Decoder(io.AgentDevError) {
  use field_stage <- decode.field("stage", decode.string)
  use field_message <- decode.field("message", decode.string)
  decode.success(io.AgentDevError(
    stage: field_stage,
    message: field_message,
  ))
}

/// Typed codec for `io.AgentDevError` (activity and workflow I/O).
pub fn agent_dev_error_codec() -> codec.Codec(io.AgentDevError) {
  codec.json_codec(agent_dev_error_to_json, agent_dev_error_decoder())
}

/// Encodes `io.AgentDevStatus` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn agent_dev_status_to_json(value: io.AgentDevStatus) -> json.Json {
  json.object([
    #("phase", json.string(value.phase)),
    #("round", json.int(value.round)),
  ])
}

/// Decoder for `io.AgentDevStatus` from schema-shaped JSON.
pub fn agent_dev_status_decoder() -> decode.Decoder(io.AgentDevStatus) {
  use field_phase <- decode.field("phase", decode.string)
  use field_round <- decode.field("round", decode.int)
  decode.success(io.AgentDevStatus(
    phase: field_phase,
    round: field_round,
  ))
}

/// Typed codec for `io.AgentDevStatus` (activity and workflow I/O).
pub fn agent_dev_status_codec() -> codec.Codec(io.AgentDevStatus) {
  codec.json_codec(agent_dev_status_to_json, agent_dev_status_decoder())
}

/// Encodes `io.Disposition` as its wire string.
pub fn disposition_to_json(value: io.Disposition) -> json.Json {
  case value {
    io.Passed -> json.string("passed")
    io.ReviewCapExhausted -> json.string("review_cap_exhausted")
    io.GateCapExhausted -> json.string("gate_cap_exhausted")
  }
}

/// Decoder for `io.Disposition` from its wire string.
pub fn disposition_decoder() -> decode.Decoder(io.Disposition) {
  decode.then(decode.string, fn(raw) {
    case raw {
      "passed" -> decode.success(io.Passed)
      "review_cap_exhausted" -> decode.success(io.ReviewCapExhausted)
      "gate_cap_exhausted" -> decode.success(io.GateCapExhausted)
      _ -> decode.failure(io.Passed, "Disposition")
    }
  })
}

/// Typed codec for `io.Disposition` (activity and workflow I/O).
pub fn disposition_codec() -> codec.Codec(io.Disposition) {
  codec.json_codec(disposition_to_json, disposition_decoder())
}

/// Encodes `io.GateDetail` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn gate_detail_to_json(value: io.GateDetail) -> json.Json {
  json.object([
    #("pass", json.bool(value.pass)),
    #("diagnostics", json.string(value.diagnostics)),
  ])
}

/// Decoder for `io.GateDetail` from schema-shaped JSON.
pub fn gate_detail_decoder() -> decode.Decoder(io.GateDetail) {
  use field_pass <- decode.field("pass", decode.bool)
  use field_diagnostics <- decode.field("diagnostics", decode.string)
  decode.success(io.GateDetail(
    pass: field_pass,
    diagnostics: field_diagnostics,
  ))
}

/// Typed codec for `io.GateDetail` (activity and workflow I/O).
pub fn gate_detail_codec() -> codec.Codec(io.GateDetail) {
  codec.json_codec(gate_detail_to_json, gate_detail_decoder())
}

/// Encodes `io.Input` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn input_to_json(value: io.Input) -> json.Json {
  json.object([
    #("repo_url", json.string(value.repo_url)),
    #("base_ref", json.string(value.base_ref)),
    #("brief_id", json.string(value.brief_id)),
    #("brief", json.string(value.brief)),
    #("design_notes", json.string(value.design_notes)),
    #("acceptance", json.array(value.acceptance, json.string)),
    #("dev_review_cap", json.int(value.dev_review_cap)),
    #("gate_cap", json.int(value.gate_cap)),
  ])
}

/// Decoder for `io.Input` from schema-shaped JSON.
pub fn input_decoder() -> decode.Decoder(io.Input) {
  use field_repo_url <- decode.field("repo_url", decode.string)
  use field_base_ref <- decode.field("base_ref", decode.string)
  use field_brief_id <- decode.field("brief_id", decode.string)
  use field_brief <- decode.field("brief", decode.string)
  use field_design_notes <- decode.field("design_notes", decode.string)
  use field_acceptance <- decode.field("acceptance", decode.list(decode.string))
  use field_dev_review_cap <- decode.field("dev_review_cap", decode.int)
  use field_gate_cap <- decode.field("gate_cap", decode.int)
  decode.success(io.Input(
    repo_url: field_repo_url,
    base_ref: field_base_ref,
    brief_id: field_brief_id,
    brief: field_brief,
    design_notes: field_design_notes,
    acceptance: field_acceptance,
    dev_review_cap: field_dev_review_cap,
    gate_cap: field_gate_cap,
  ))
}

/// Typed codec for `io.Input` (activity and workflow I/O).
pub fn input_codec() -> codec.Codec(io.Input) {
  codec.json_codec(input_to_json, input_decoder())
}

/// Encodes `io.LandInput` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn land_input_to_json(value: io.LandInput) -> json.Json {
  json.object([
    #("workspace", workspace_to_json(value.workspace)),
    #("brief_id", json.string(value.brief_id)),
  ])
}

/// Decoder for `io.LandInput` from schema-shaped JSON.
pub fn land_input_decoder() -> decode.Decoder(io.LandInput) {
  use field_workspace <- decode.field("workspace", workspace_decoder())
  use field_brief_id <- decode.field("brief_id", decode.string)
  decode.success(io.LandInput(
    workspace: field_workspace,
    brief_id: field_brief_id,
  ))
}

/// Typed codec for `io.LandInput` (activity and workflow I/O).
pub fn land_input_codec() -> codec.Codec(io.LandInput) {
  codec.json_codec(land_input_to_json, land_input_decoder())
}

/// Encodes `io.LandOutput` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn land_output_to_json(value: io.LandOutput) -> json.Json {
  json.object([
    #("commit_sha", json.string(value.commit_sha)),
  ])
}

/// Decoder for `io.LandOutput` from schema-shaped JSON.
pub fn land_output_decoder() -> decode.Decoder(io.LandOutput) {
  use field_commit_sha <- decode.field("commit_sha", decode.string)
  decode.success(io.LandOutput(
    commit_sha: field_commit_sha,
  ))
}

/// Typed codec for `io.LandOutput` (activity and workflow I/O).
pub fn land_output_codec() -> codec.Codec(io.LandOutput) {
  codec.json_codec(land_output_to_json, land_output_decoder())
}

/// Encodes `io.Output` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn output_to_json(value: io.Output) -> json.Json {
  json.object([
    #("disposition", disposition_to_json(value.disposition)),
    #("dev_review_rounds", json.int(value.dev_review_rounds)),
    #("gate_rounds", json.int(value.gate_rounds)),
    #("last_review", review_verdict_to_json(value.last_review)),
    #("gate_detail", gate_detail_to_json(value.gate_detail)),
    #("branch", json.string(value.branch)),
    #("workspace_path", json.string(value.workspace_path)),
  ])
}

/// Decoder for `io.Output` from schema-shaped JSON.
pub fn output_decoder() -> decode.Decoder(io.Output) {
  use field_disposition <- decode.field("disposition", disposition_decoder())
  use field_dev_review_rounds <- decode.field("dev_review_rounds", decode.int)
  use field_gate_rounds <- decode.field("gate_rounds", decode.int)
  use field_last_review <- decode.field("last_review", review_verdict_decoder())
  use field_gate_detail <- decode.field("gate_detail", gate_detail_decoder())
  use field_branch <- decode.field("branch", decode.string)
  use field_workspace_path <- decode.field("workspace_path", decode.string)
  decode.success(io.Output(
    disposition: field_disposition,
    dev_review_rounds: field_dev_review_rounds,
    gate_rounds: field_gate_rounds,
    last_review: field_last_review,
    gate_detail: field_gate_detail,
    branch: field_branch,
    workspace_path: field_workspace_path,
  ))
}

/// Typed codec for `io.Output` (activity and workflow I/O).
pub fn output_codec() -> codec.Codec(io.Output) {
  codec.json_codec(output_to_json, output_decoder())
}

/// Encodes `io.ProvisionInput` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn provision_input_to_json(value: io.ProvisionInput) -> json.Json {
  json.object([
    #("repo_url", json.string(value.repo_url)),
    #("base_ref", json.string(value.base_ref)),
    #("brief_id", json.string(value.brief_id)),
    #("run_id", json.string(value.run_id)),
  ])
}

/// Decoder for `io.ProvisionInput` from schema-shaped JSON.
pub fn provision_input_decoder() -> decode.Decoder(io.ProvisionInput) {
  use field_repo_url <- decode.field("repo_url", decode.string)
  use field_base_ref <- decode.field("base_ref", decode.string)
  use field_brief_id <- decode.field("brief_id", decode.string)
  use field_run_id <- decode.field("run_id", decode.string)
  decode.success(io.ProvisionInput(
    repo_url: field_repo_url,
    base_ref: field_base_ref,
    brief_id: field_brief_id,
    run_id: field_run_id,
  ))
}

/// Typed codec for `io.ProvisionInput` (activity and workflow I/O).
pub fn provision_input_codec() -> codec.Codec(io.ProvisionInput) {
  codec.json_codec(provision_input_to_json, provision_input_decoder())
}

/// Encodes `io.ReviewVerdict` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn review_verdict_to_json(value: io.ReviewVerdict) -> json.Json {
  json.object([
    #("pass", json.bool(value.pass)),
    #("blockers", json.array(value.blockers, json.string)),
    #("summary", json.string(value.summary)),
  ])
}

/// Decoder for `io.ReviewVerdict` from schema-shaped JSON.
pub fn review_verdict_decoder() -> decode.Decoder(io.ReviewVerdict) {
  use field_pass <- decode.field("pass", decode.bool)
  use field_blockers <- decode.field("blockers", decode.list(decode.string))
  use field_summary <- decode.field("summary", decode.string)
  decode.success(io.ReviewVerdict(
    pass: field_pass,
    blockers: field_blockers,
    summary: field_summary,
  ))
}

/// Typed codec for `io.ReviewVerdict` (activity and workflow I/O).
pub fn review_verdict_codec() -> codec.Codec(io.ReviewVerdict) {
  codec.json_codec(review_verdict_to_json, review_verdict_decoder())
}

/// Encodes `io.Workspace` as schema-shaped JSON; optional fields are
/// omitted when `None`.
pub fn workspace_to_json(value: io.Workspace) -> json.Json {
  json.object([
    #("path", json.string(value.path)),
    #("branch", json.string(value.branch)),
  ])
}

/// Decoder for `io.Workspace` from schema-shaped JSON.
pub fn workspace_decoder() -> decode.Decoder(io.Workspace) {
  use field_path <- decode.field("path", decode.string)
  use field_branch <- decode.field("branch", decode.string)
  decode.success(io.Workspace(
    path: field_path,
    branch: field_branch,
  ))
}

/// Typed codec for `io.Workspace` (activity and workflow I/O).
pub fn workspace_codec() -> codec.Codec(io.Workspace) {
  codec.json_codec(workspace_to_json, workspace_decoder())
}
