//// Generated by aion generate — do not edit; regenerate from the activity declarations.
////
//// Wire-compat goldens for the `aion_order_saga` remote activities: each test pins
//// a value type's encoded wire shape against a literal derived from its type.

import aion_order_saga_codecs as codecs
import aion_order_saga_io as io
import gleam/json
import gleeunit/should

pub fn order_input_wire_test() {
  codecs.order_input_to_json(io.OrderInput(order_id: "", item: "", quantity: 0, amount: 0))
  |> json.to_string
  |> should.equal("{\"order_id\":\"\",\"item\":\"\",\"quantity\":0,\"amount\":0}")
}

pub fn inventory_reservation_wire_test() {
  codecs.inventory_reservation_to_json(io.InventoryReservation(order_id: "", reservation_id: "", item: "", quantity: 0))
  |> json.to_string
  |> should.equal("{\"order_id\":\"\",\"reservation_id\":\"\",\"item\":\"\",\"quantity\":0}")
}

pub fn payment_receipt_wire_test() {
  codecs.payment_receipt_to_json(io.PaymentReceipt(order_id: "", payment_id: "", amount: 0))
  |> json.to_string
  |> should.equal("{\"order_id\":\"\",\"payment_id\":\"\",\"amount\":0}")
}

pub fn shipment_wire_test() {
  codecs.shipment_to_json(io.Shipment(order_id: "", shipment_id: ""))
  |> json.to_string
  |> should.equal("{\"order_id\":\"\",\"shipment_id\":\"\"}")
}

pub fn release_inventory_input_wire_test() {
  codecs.release_inventory_input_to_json(io.ReleaseInventoryInput(order_id: "", reservation_id: "", item: "", quantity: 0))
  |> json.to_string
  |> should.equal("{\"order_id\":\"\",\"reservation_id\":\"\",\"item\":\"\",\"quantity\":0}")
}

pub fn compensation_output_wire_test() {
  codecs.compensation_output_to_json(io.CompensationOutput(status: "", detail: ""))
  |> json.to_string
  |> should.equal("{\"status\":\"\",\"detail\":\"\"}")
}

pub fn refund_payment_input_wire_test() {
  codecs.refund_payment_input_to_json(io.RefundPaymentInput(order_id: "", payment_id: "", amount: 0))
  |> json.to_string
  |> should.equal("{\"order_id\":\"\",\"payment_id\":\"\",\"amount\":0}")
}

pub fn cancel_shipment_input_wire_test() {
  codecs.cancel_shipment_input_to_json(io.CancelShipmentInput(order_id: "", shipment_id: ""))
  |> json.to_string
  |> should.equal("{\"order_id\":\"\",\"shipment_id\":\"\"}")
}
