//// Generated by aion generate — a test scaffold to fill in, not a do-not-edit file.
////
//// A pure `aion/testing` scenario for the `order_saga` workflow: each activity
//// is mocked with a happy-path output and the entry function is asserted to
//// replay deterministically. The mocks were filled in from the generated
//// scaffold; the harness needs no engine, store, or beamr.

import aion/testing
import aion_order_saga_activity_wrappers as wrappers
import aion_order_saga_io as io
import gleeunit
import order_saga

pub fn main() {
  gleeunit.main()
}

/// The happy-path order every mock in this scenario agrees on.
fn order() -> io.OrderInput {
  io.OrderInput(order_id: "o-1001", item: "widget", quantity: 2, amount: 4200)
}

/// Replay-determinism scenario for `order_saga.execute`: every step succeeds,
/// the saga ships the order, and the observable command sequence is identical
/// on replay.
pub fn replay_determinism_scaffold_test() {
  let assert Ok(env) = testing.new()

  // One typed mock per declared activity, returning this scenario's output.
  let assert Ok(env) =
    testing.mock_activity(env, wrappers.reserve_inventory_activity(order()), fn(_input) {
      Ok(io.InventoryReservation(
        order_id: "o-1001",
        reservation_id: "res-1",
        item: "widget",
        quantity: 2,
      ))
    })
  let assert Ok(env) =
    testing.mock_activity(env, wrappers.charge_payment_activity(order()), fn(_input) {
      Ok(io.PaymentReceipt(order_id: "o-1001", payment_id: "pay-1", amount: 4200))
    })
  let assert Ok(env) =
    testing.mock_activity(env, wrappers.ship_order_activity(order()), fn(_input) {
      Ok(io.Shipment(order_id: "o-1001", shipment_id: "ship-1"))
    })
  // The compensations never run on the happy path, but the scaffold mocks the
  // full declared surface so a failing step cannot hit an unmocked activity.
  let assert Ok(env) =
    testing.mock_activity(
      env,
      wrappers.release_inventory_activity(io.ReleaseInventoryInput(
        order_id: "o-1001",
        reservation_id: "res-1",
        item: "widget",
        quantity: 2,
      )),
      fn(_input) { Ok(io.CompensationOutput(status: "released", detail: "")) },
    )
  let assert Ok(env) =
    testing.mock_activity(
      env,
      wrappers.refund_payment_activity(io.RefundPaymentInput(
        order_id: "o-1001",
        payment_id: "pay-1",
        amount: 4200,
      )),
      fn(_input) { Ok(io.CompensationOutput(status: "refunded", detail: "")) },
    )
  let assert Ok(env) =
    testing.mock_activity(
      env,
      wrappers.cancel_shipment_activity(io.CancelShipmentInput(
        order_id: "o-1001",
        shipment_id: "ship-1",
      )),
      fn(_input) { Ok(io.CompensationOutput(status: "cancelled", detail: "")) },
    )

  // This workflow arms no durable timers, so the clock is not advanced.

  // Drive the typed entry function and assert it replays deterministically.
  let result = testing.assert_replay(env, fn() { order_saga.execute(order()) })
  let assert Ok(shipment) = result
  assert shipment == io.Shipment(order_id: "o-1001", shipment_id: "ship-1")
}
