# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import worker_pb2 as worker__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerProtocolStub(object):
    """WorkerProtocol is one long-lived gRPC bidirectional stream. A worker sends
    RegisterWorker first, then ActivityResult and Heartbeat messages. The server
    pushes ActivityTask messages down the same stream; there is no polling RPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamWorker = channel.stream_stream(
                '/aion.WorkerProtocol/StreamWorker',
                request_serializer=worker__pb2.WorkerToServer.SerializeToString,
                response_deserializer=worker__pb2.ServerToWorker.FromString,
                _registered_method=True)


class WorkerProtocolServicer(object):
    """WorkerProtocol is one long-lived gRPC bidirectional stream. A worker sends
    RegisterWorker first, then ActivityResult and Heartbeat messages. The server
    pushes ActivityTask messages down the same stream; there is no polling RPC.
    """

    def StreamWorker(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerProtocolServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamWorker': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamWorker,
                    request_deserializer=worker__pb2.WorkerToServer.FromString,
                    response_serializer=worker__pb2.ServerToWorker.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aion.WorkerProtocol', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aion.WorkerProtocol', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerProtocol(object):
    """WorkerProtocol is one long-lived gRPC bidirectional stream. A worker sends
    RegisterWorker first, then ActivityResult and Heartbeat messages. The server
    pushes ActivityTask messages down the same stream; there is no polling RPC.
    """

    @staticmethod
    def StreamWorker(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/aion.WorkerProtocol/StreamWorker',
            worker__pb2.WorkerToServer.SerializeToString,
            worker__pb2.ServerToWorker.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
