# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import workflow_pb2 as workflow__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in workflow_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkflowServiceStub:
    """Workflow-management API shared by clients and the managed server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartWorkflow = channel.unary_unary(
                '/aion.WorkflowService/StartWorkflow',
                request_serializer=workflow__pb2.StartWorkflowRequest.SerializeToString,
                response_deserializer=workflow__pb2.StartWorkflowResponse.FromString,
                _registered_method=True)
        self.Signal = channel.unary_unary(
                '/aion.WorkflowService/Signal',
                request_serializer=workflow__pb2.SignalRequest.SerializeToString,
                response_deserializer=workflow__pb2.SignalResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/aion.WorkflowService/Query',
                request_serializer=workflow__pb2.QueryRequest.SerializeToString,
                response_deserializer=workflow__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/aion.WorkflowService/Cancel',
                request_serializer=workflow__pb2.CancelRequest.SerializeToString,
                response_deserializer=workflow__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.ListWorkflows = channel.unary_unary(
                '/aion.WorkflowService/ListWorkflows',
                request_serializer=workflow__pb2.ListWorkflowsRequest.SerializeToString,
                response_deserializer=workflow__pb2.ListWorkflowsResponse.FromString,
                _registered_method=True)
        self.CountWorkflows = channel.unary_unary(
                '/aion.WorkflowService/CountWorkflows',
                request_serializer=workflow__pb2.CountWorkflowsRequest.SerializeToString,
                response_deserializer=workflow__pb2.CountWorkflowsResponse.FromString,
                _registered_method=True)
        self.DescribeWorkflow = channel.unary_unary(
                '/aion.WorkflowService/DescribeWorkflow',
                request_serializer=workflow__pb2.DescribeWorkflowRequest.SerializeToString,
                response_deserializer=workflow__pb2.DescribeWorkflowResponse.FromString,
                _registered_method=True)
        self.CreateSchedule = channel.unary_unary(
                '/aion.WorkflowService/CreateSchedule',
                request_serializer=workflow__pb2.CreateScheduleRequest.SerializeToString,
                response_deserializer=workflow__pb2.CreateScheduleResponse.FromString,
                _registered_method=True)
        self.UpdateSchedule = channel.unary_unary(
                '/aion.WorkflowService/UpdateSchedule',
                request_serializer=workflow__pb2.UpdateScheduleRequest.SerializeToString,
                response_deserializer=workflow__pb2.UpdateScheduleResponse.FromString,
                _registered_method=True)
        self.PauseSchedule = channel.unary_unary(
                '/aion.WorkflowService/PauseSchedule',
                request_serializer=workflow__pb2.ScheduleIdRequest.SerializeToString,
                response_deserializer=workflow__pb2.PauseScheduleResponse.FromString,
                _registered_method=True)
        self.ResumeSchedule = channel.unary_unary(
                '/aion.WorkflowService/ResumeSchedule',
                request_serializer=workflow__pb2.ScheduleIdRequest.SerializeToString,
                response_deserializer=workflow__pb2.ResumeScheduleResponse.FromString,
                _registered_method=True)
        self.DeleteSchedule = channel.unary_unary(
                '/aion.WorkflowService/DeleteSchedule',
                request_serializer=workflow__pb2.ScheduleIdRequest.SerializeToString,
                response_deserializer=workflow__pb2.DeleteScheduleResponse.FromString,
                _registered_method=True)
        self.ListSchedules = channel.unary_unary(
                '/aion.WorkflowService/ListSchedules',
                request_serializer=workflow__pb2.ListSchedulesRequest.SerializeToString,
                response_deserializer=workflow__pb2.ListSchedulesResponse.FromString,
                _registered_method=True)
        self.DescribeSchedule = channel.unary_unary(
                '/aion.WorkflowService/DescribeSchedule',
                request_serializer=workflow__pb2.ScheduleIdRequest.SerializeToString,
                response_deserializer=workflow__pb2.DescribeScheduleResponse.FromString,
                _registered_method=True)


class WorkflowServiceServicer:
    """Workflow-management API shared by clients and the managed server.
    """

    def StartWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Signal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkflows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountWorkflows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSchedules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkflowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.StartWorkflow,
                    request_deserializer=workflow__pb2.StartWorkflowRequest.FromString,
                    response_serializer=workflow__pb2.StartWorkflowResponse.SerializeToString,
            ),
            'Signal': grpc.unary_unary_rpc_method_handler(
                    servicer.Signal,
                    request_deserializer=workflow__pb2.SignalRequest.FromString,
                    response_serializer=workflow__pb2.SignalResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=workflow__pb2.QueryRequest.FromString,
                    response_serializer=workflow__pb2.QueryResponse.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=workflow__pb2.CancelRequest.FromString,
                    response_serializer=workflow__pb2.CancelResponse.SerializeToString,
            ),
            'ListWorkflows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkflows,
                    request_deserializer=workflow__pb2.ListWorkflowsRequest.FromString,
                    response_serializer=workflow__pb2.ListWorkflowsResponse.SerializeToString,
            ),
            'CountWorkflows': grpc.unary_unary_rpc_method_handler(
                    servicer.CountWorkflows,
                    request_deserializer=workflow__pb2.CountWorkflowsRequest.FromString,
                    response_serializer=workflow__pb2.CountWorkflowsResponse.SerializeToString,
            ),
            'DescribeWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeWorkflow,
                    request_deserializer=workflow__pb2.DescribeWorkflowRequest.FromString,
                    response_serializer=workflow__pb2.DescribeWorkflowResponse.SerializeToString,
            ),
            'CreateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSchedule,
                    request_deserializer=workflow__pb2.CreateScheduleRequest.FromString,
                    response_serializer=workflow__pb2.CreateScheduleResponse.SerializeToString,
            ),
            'UpdateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSchedule,
                    request_deserializer=workflow__pb2.UpdateScheduleRequest.FromString,
                    response_serializer=workflow__pb2.UpdateScheduleResponse.SerializeToString,
            ),
            'PauseSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseSchedule,
                    request_deserializer=workflow__pb2.ScheduleIdRequest.FromString,
                    response_serializer=workflow__pb2.PauseScheduleResponse.SerializeToString,
            ),
            'ResumeSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeSchedule,
                    request_deserializer=workflow__pb2.ScheduleIdRequest.FromString,
                    response_serializer=workflow__pb2.ResumeScheduleResponse.SerializeToString,
            ),
            'DeleteSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSchedule,
                    request_deserializer=workflow__pb2.ScheduleIdRequest.FromString,
                    response_serializer=workflow__pb2.DeleteScheduleResponse.SerializeToString,
            ),
            'ListSchedules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSchedules,
                    request_deserializer=workflow__pb2.ListSchedulesRequest.FromString,
                    response_serializer=workflow__pb2.ListSchedulesResponse.SerializeToString,
            ),
            'DescribeSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeSchedule,
                    request_deserializer=workflow__pb2.ScheduleIdRequest.FromString,
                    response_serializer=workflow__pb2.DescribeScheduleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aion.WorkflowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aion.WorkflowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkflowService:
    """Workflow-management API shared by clients and the managed server.
    """

    @staticmethod
    def StartWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aion.WorkflowService/StartWorkflow',
            workflow__pb2.StartWorkflowRequest.SerializeToString,
            workflow__pb2.StartWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Signal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aion.WorkflowService/Signal',
            workflow__pb2.SignalRequest.SerializeToString,
            workflow__pb2.SignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aion.WorkflowService/Query',
            workflow__pb2.QueryRequest.SerializeToString,
            workflow__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aion.WorkflowService/Cancel',
            workflow__pb2.CancelRequest.SerializeToString,
            workflow__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkflows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aion.WorkflowService/ListWorkflows',
            workflow__pb2.ListWorkflowsRequest.SerializeToString,
            workflow__pb2.ListWorkflowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountWorkflows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aion.WorkflowService/CountWorkflows',
            workflow__pb2.CountWorkflowsRequest.SerializeToString,
            workflow__pb2.CountWorkflowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aion.WorkflowService/DescribeWorkflow',
            workflow__pb2.DescribeWorkflowRequest.SerializeToString,
            workflow__pb2.DescribeWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aion.WorkflowService/CreateSchedule',
            workflow__pb2.CreateScheduleRequest.SerializeToString,
            workflow__pb2.CreateScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aion.WorkflowService/UpdateSchedule',
            workflow__pb2.UpdateScheduleRequest.SerializeToString,
            workflow__pb2.UpdateScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aion.WorkflowService/PauseSchedule',
            workflow__pb2.ScheduleIdRequest.SerializeToString,
            workflow__pb2.PauseScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aion.WorkflowService/ResumeSchedule',
            workflow__pb2.ScheduleIdRequest.SerializeToString,
            workflow__pb2.ResumeScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aion.WorkflowService/DeleteSchedule',
            workflow__pb2.ScheduleIdRequest.SerializeToString,
            workflow__pb2.DeleteScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aion.WorkflowService/ListSchedules',
            workflow__pb2.ListSchedulesRequest.SerializeToString,
            workflow__pb2.ListSchedulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aion.WorkflowService/DescribeSchedule',
            workflow__pb2.ScheduleIdRequest.SerializeToString,
            workflow__pb2.DescribeScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
